// js/strengths/doksuri.en.js — 03 AI · AI at work, already.
// Generated by lab/formats/port-scenes.mjs from the approved prototype lab/formats/live/doksuri/index.html and its
// English pairs (en.json). Change those and regenerate (node lab/formats/port-scenes.mjs); do not edit this file by hand.
export const css = `:host {
  --ink: #EDE9E7; --ink2: rgba(237,233,231,.78); --ink3: rgba(237,233,231,.6); --ink4: rgba(237,233,231,.32);
  --teal: #10C4BE; --teal2: #63DDD7; --cyan: #BFF3F0; --warm: #F4D7B8; --amber: #FFC285; --red: #FF6B76;
  --bg: #01080a; --panel: #041114; --panel2: #071a1f; --panel3: #0c2329;
  --line: rgba(237,233,231,.12); --line2: rgba(237,233,231,.2); --line3: rgba(237,233,231,.32);
  --teal-a1: rgba(16,196,190,.10); --teal-a2: rgba(16,196,190,.22); --teal-a3: rgba(16,196,190,.42);
  --amber-a1: rgba(255,194,133,.09); --amber-a2: rgba(255,194,133,.34);
  --font: "Pretendard Variable", Pretendard, -apple-system, BlinkMacSystemFont, "Apple SD Gothic Neo", "Noto Sans KR", sans-serif;
  --mono: "IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, "Pretendard Variable", Pretendard, monospace;
}
*, *::before, *::after { box-sizing: border-box; }
:host {    color: var(--ink); font-family: var(--font); -webkit-font-smoothing: antialiased; letter-spacing: -.005em; }
.mono { font-family: var(--mono); letter-spacing: 0; }
.msg { position: absolute; z-index: 10; left: 72px; top: 196px; width: 440px; }
.kick { display: flex; align-items: baseline; gap: 7px; font: 400 13px var(--mono); color: var(--ink); }
.kick .area { font-family: var(--font); font-size: 13.5px; color: var(--teal); }
.hook { margin: 20px 0 0; font-size: 50px; line-height: 1.06; font-weight: 600; letter-spacing: -.03em; }
.lede { margin: 26px 0 0; font-size: 17.5px; line-height: 1.72; font-weight: 500; word-break: keep-all; }
.more { display: inline-flex; gap: 8px; margin-top: 30px; padding-bottom: 4px; font-size: 14px; color: var(--ink2); border-bottom: 1px solid var(--line3); }
.hint { font-size: 12.5px; color: var(--ink3); }
.fx-tag { display: inline-flex; align-items: center; height: 18px; padding: 0 5px; border: 1px solid var(--line2); border-radius: 4px; font: 500 11px/1 var(--mono); letter-spacing: .03em; color: var(--ink3); white-space: nowrap; }
.fx-tag.tool { color: var(--teal2); border-color: var(--teal-a3); }
.fx-tag.ai { color: var(--cyan); border-color: rgba(191,243,240,.35); }
.fx-tag.human { color: var(--warm); border-color: rgba(244,215,184,.45); }
.fx-demo { display: inline-flex; align-items: center; height: 22px; padding: 0 7px; border-radius: 5px; border: 1px solid var(--amber-a2); font: 500 11px var(--mono); color: var(--amber); letter-spacing: .02em; }
.fx-panel { background: var(--panel); border: 1px solid var(--line); border-radius: 14px; }
.m-only { display: none; }
:host(.m) .msg { position: relative; left: auto; top: auto; width: auto; padding: 84px 20px 0; }
:host(.m) .kick { font-size: 12px; }
:host(.m) .kick .area { font-size: 12.5px; }
:host(.m) .hook { margin-top: 12px; font-size: 31px; line-height: 1.12; }
:host(.m) .lede { margin-top: 14px; font-size: 14.5px; line-height: 1.62; }
:host(.m) .more { display: none; }
:host(.m) .d-only { display: none !important; }
:host(.m) .m-only { display: block; }
:host(:not(.m)) .msg.narrow { width: 410px; }
.key { margin: 30px 0 0; padding: 0; list-style: none; border-top: 1px solid var(--line); }
.key li { display: grid; grid-template-columns: 62px 1fr; gap: 10px; align-items: center; padding: 10px 0; border-bottom: 1px solid var(--line); font-size: 13.5px; color: var(--ink2); }
.key li b { color: var(--ink); font-weight: 500; margin-right: 6px; }
.key li .fx-tag { justify-self: start; }
.board { position: absolute; z-index: 6; left: 520px; top: 164px; width: 530px; height: 480px; display: flex; flex-direction: column; overflow: hidden; }
.bar { display: flex; align-items: center; gap: 10px; height: 50px; padding: 0 16px; border-bottom: 1px solid var(--line); }
.bar .nm { font-size: 15px; font-weight: 600; }
.bar .ko { font-size: 12px; color: var(--ink3); }
.bar .tg { font: 400 11px var(--mono); color: var(--teal2); }
.bar .fx-demo { margin-left: auto; }
.agents { display: flex; flex-wrap: wrap; gap: 6px 8px; padding: 12px 16px; border-bottom: 1px solid var(--line); }
.ag { display: inline-flex; align-items: center; gap: 6px; height: 28px; padding: 0 10px 0 6px; border: 1px solid var(--line); border-radius: 8px; background: var(--panel2); font-size: 12.5px; }
.ag em { font-style: normal; color: var(--ink3); font-size: 11.5px; }
.cols { flex: 1; display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; padding: 12px 14px 4px; min-height: 0; }
.col h4 { margin: 2px 2px 10px; font-size: 12px; font-weight: 600; color: var(--ink2); display: flex; align-items: center; gap: 7px; }
.col h4 .st { width: 7px; height: 7px; border-radius: 50%; }
.card { margin-bottom: 9px; padding: 10px 10px 9px; border: 1px solid var(--line); border-radius: 10px; background: var(--panel2); }
.card .f { font: 400 10.5px var(--mono); color: var(--ink3); }
.card .t { margin: 4px 0 8px; font-size: 13.5px; font-weight: 600; line-height: 1.35; word-break: keep-all; }
.card .who { display: flex; flex-wrap: wrap; gap: 4px; align-items: center; font-size: 11.5px; color: var(--ink2); }
.card .who + .who { margin-top: 5px; }
.card .ok { color: var(--teal2); font-size: 11.5px; font-weight: 500; }
.card .run { color: var(--cyan); font-size: 11.5px; }
.card.hot { border-color: rgba(244,215,184,.55); box-shadow: 0 0 0 1px rgba(244,215,184,.18), 0 0 22px rgba(255,194,133,.12); }
.diff { margin: 2px 0 8px; padding: 6px 8px; border-radius: 6px; background: #020c0e; font-size: 12px; line-height: 1.6; }
.diff b { font: 500 11px var(--mono); margin-right: 5px; }
.diff .m { color: #FF9AA2; }
.diff .p { color: var(--teal2); }
.acts { display: flex; gap: 6px; margin-top: 8px; }
.btn { display: inline-flex; align-items: center; height: 26px; padding: 0 10px; border-radius: 7px; font-size: 12px; border: 1px solid var(--line2); color: var(--ink2); }
.btn.go { border-color: rgba(244,215,184,.6); color: var(--warm); background: rgba(255,194,133,.08); }
.sync { display: flex; align-items: center; gap: 8px; height: 38px; padding: 0 16px; border-top: 1px solid var(--line); font-size: 12px; color: var(--ink3); }
.sync .mono { font-size: 11px; }
.sync i { width: 6px; height: 6px; border-radius: 50%; background: var(--teal); box-shadow: 0 0 6px var(--teal); }
.chat { position: absolute; z-index: 6; left: 1066px; top: 164px; width: 302px; height: 480px; display: flex; flex-direction: column; }
.ch { display: flex; align-items: center; gap: 10px; height: 50px; padding: 0 14px; border-bottom: 1px solid var(--line); }
.av { width: 26px; height: 26px; border-radius: 8px; background: #031214; border: 1px solid var(--teal-a3); display: grid; place-items: center; }
.av i { display: block; width: 11px; height: 3px; border-radius: 1px; background: var(--teal); box-shadow: 0 0 6px var(--teal); margin-top: 8px; }
.ch b { font-size: 14px; font-weight: 600; }
.ch span { display: block; font-size: 11.5px; color: var(--ink3); }
.log { flex: 1; padding: 14px; display: flex; flex-direction: column; gap: 12px; min-height: 0; overflow: hidden; }
.me { align-self: flex-end; max-width: 84%; padding: 8px 11px; border-radius: 12px 12px 3px 12px; background: var(--panel3); border: 1px solid var(--line2); font-size: 13px; line-height: 1.5; }
.ai { font-size: 13.5px; line-height: 1.62; word-break: keep-all; }
.ai .who { display: block; margin-bottom: 3px; font: 400 11.5px var(--mono); color: var(--teal); }
.ref { color: var(--ink); border-bottom: 1px dashed rgba(99,221,215,.6); }
.ref.h { border-bottom-color: rgba(244,215,184,.7); }
.ai .btn { margin-top: 9px; }
.sug { display: flex; flex-wrap: wrap; gap: 6px; padding: 12px 14px 14px; border-top: 1px solid var(--line); }
.chip { display: inline-flex; align-items: center; height: 30px; padding: 0 11px; border-radius: 15px; border: 1px solid var(--teal-a3); color: var(--teal2); font-size: 12.5px; background: rgba(16,196,190,.06); }
.under { position: absolute; z-index: 6; left: 520px; top: 660px; }
.mchat { position: relative; z-index: 10; margin: 18px 16px 0; }
.mchat .log { padding: 12px; gap: 10px; }
.mchat .ch { height: 44px; padding: 0 12px; }
.mb { margin-top: 8px; border: 1px solid var(--line); border-radius: 10px; overflow: hidden; }
.mb .r { display: grid; grid-template-columns: 1fr auto; gap: 8px; align-items: center; padding: 8px 10px; border-top: 1px solid var(--line); background: var(--panel2); }
.mb .r:first-child { border-top: 0; }
.mb .r .t { font-size: 12.5px; font-weight: 600; }
.mb .r .s { display: block; margin-top: 2px; font-size: 11px; color: var(--ink3); }
.mb .r.hot { background: rgba(255,194,133,.07); }
.mb .h { display: flex; align-items: center; gap: 6px; padding: 7px 10px; font: 400 10.5px var(--mono); color: var(--ink3); background: var(--panel); }
.mhint { margin: 8px 20px 0; position: relative; z-index: 10; }
:host(.m) .mchat .me { font-size: 12.5px; }
:host(.m) .mchat .ai { font-size: 13px; line-height: 1.55; }
:host(.m) .mchat .sug { padding: 10px 12px 12px; }
:host(.m) .mchat .chip { height: 28px; font-size: 12px; }
:host(.pre) .msg > *, :host(.pre) .board, :host(.pre) .chat, :host(.pre) .mchat, :host(.pre) .under, :host(.pre) .mhint { opacity: 0; }
.card, .ag, .sync, .mb .r { position: relative; }
.cols { grid-template-rows: minmax(0, 1fr); }
.col { min-height: 0; }
.col.over { position: relative; clip-path: inset(-60px -700px 0 -700px); }
.col.over::after { content: ''; position: absolute; left: -6px; right: -6px; bottom: 0; height: 36px; z-index: 4; pointer-events: none; background: linear-gradient(rgba(4,17,20,0), #041114 88%); }
.chat .sug { min-height: 57px; }
.btn, .chip { cursor: pointer; user-select: none; -webkit-user-select: none; -webkit-tap-highlight-color: transparent; }
.acts .btn:not(.go) { cursor: default; }
.btn.off { opacity: .4; pointer-events: none; }
.ag .pd { position: absolute; top: -3px; right: -3px; width: 7px; height: 7px; border-radius: 50%; background: var(--cyan); box-shadow: 0 0 0 2px #041114, 0 0 8px rgba(191,243,240,.65); }
.run.shim { color: transparent; -webkit-background-clip: text; background-clip: text; background-image: linear-gradient(90deg, #BFF3F0 0%, #BFF3F0 38%, #F4FFFE 50%, #BFF3F0 62%, #BFF3F0 100%); background-size: 240% 100%; animation: shim 2.8s linear infinite; }
@keyframes shim { from { background-position: 100% 0; } to { background-position: -140% 0; } }
.w { opacity: 0; transition: opacity .16s linear; }
.w.on { opacity: 1; }
:host(.still) .w { transition: none; }
.dots { display: inline-flex; gap: 5px; align-items: center; height: 20px; }
.dots i { width: 5px; height: 5px; border-radius: 50%; background: var(--teal2); opacity: .25; animation: dot 1s ease-in-out infinite; }
.dots i:nth-child(2) { animation-delay: .16s; }
.dots i:nth-child(3) { animation-delay: .32s; }
@keyframes dot { 0%, 100% { opacity: .25; transform: none; } 40% { opacity: 1; transform: translateY(-2px); } }
.log.scrolled { -webkit-mask-image: linear-gradient(transparent 0, #000 28px); mask-image: linear-gradient(transparent 0, #000 28px); }
.lnk { display: inline-flex; align-items: center; height: 26px; margin-top: 9px; padding: 0 10px; border-radius: 7px; border: 1px solid var(--line2); color: var(--teal2); font-size: 12px; }
.diff .m.struck { text-decoration: line-through; text-decoration-color: rgba(255,154,162,.75); opacity: .45; }
.diff .p.lit { color: #8FF0EA; }
.seal { position: absolute; top: -10px; right: -8px; z-index: 3; width: 30px; height: 30px; border-radius: 50%; display: grid; place-items: center; background: #0a1b1e; border: 1.5px solid rgba(244,215,184,.9); box-shadow: 0 0 16px rgba(255,194,133,.32); }
.seal svg { width: 9px; height: 13px; margin-left: 2px; overflow: visible; }
.seal path { fill: var(--warm); }
.seal .ring { position: absolute; inset: -2px; border-radius: 50%; border: 1.5px solid rgba(255,194,133,.85); opacity: 0; pointer-events: none; }
.mb .seal { position: relative; top: auto; right: auto; width: 26px; height: 26px; }
.mb .seal svg { width: 8px; height: 11px; }
.pk { position: absolute; top: -1px; left: 0; width: 46px; height: 2px; pointer-events: none; opacity: 0; border-radius: 2px; background: linear-gradient(90deg, rgba(16,196,190,0), rgba(99,221,215,.75) 72%, #E8FFFD); }
.pk::after { content: ''; position: absolute; right: -7px; top: -6px; width: 14px; height: 14px; border-radius: 50%; background: radial-gradient(circle, #F4FFFE 0 2px, rgba(191,243,240,.55) 3px, rgba(16,196,190,0) 7px); }
:host(.m) .mchat.fx-panel { display: flex; flex-direction: column; max-height: var(--mh, none); }
:host(.m) .mchat .ch, :host(.m) .mchat .sug { flex: none; }
:host(.m) .mchat .log { flex: 1 1 auto; }
:host(.m) .mchat .sug { min-height: 51px; }
`;
export const html = `<div class="frame">
<section class="msg narrow">
  <div class="kick"><span>03</span><span class="area">· AI</span></div>
  <h2 class="hook">AI at work,<br>already.</h2>
  <p class="lede">Root Kernel already works with many AI&nbsp;Agents. Tools do the Deterministic work, AI does the work that needs judgment, and people make the important decisions.</p>
  <ul class="key d-only">
    <li><span class="fx-tag tool">Tool</span><span><b>Fixed work</b>Test · sync · search</span></li>
    <li><span class="fx-tag ai">AI</span><span><b>Work that needs judgment</b>Spec · code · docs</span></li>
    <li><span class="fx-tag human">Human</span><span><b>Important decisions</b>Approval</span></li>
  </ul>
  <a class="more" href="#svcDetails"></a>
</section>

<div class="visw d-only"><div class="vis"><div class="board fx-panel d-only">
  <div class="bar"><span class="nm">Doksuri</span><span class="tg">Markdown-native · two-way sync</span><span class="fx-demo">Example</span></div>
  <div class="agents">
    <span class="ag"><span class="fx-tag ai">AI</span>planner <em>proposes Specs</em></span>
    <span class="ag"><span class="fx-tag ai">AI</span>builder <em>writes code</em></span>
    <span class="ag"><span class="fx-tag ai">AI</span>writer <em>docs · comments</em></span>
    <span class="ag"><span class="fx-tag human">Human</span>owner <em>approves</em></span>
  </div>
  <div class="cols">
    <div class="col">
      <h4><span class="st" style="background:var(--cyan)"></span>In progress</h4>
      <div class="card"><div class="f">tasks/session.md</div><div class="t">Session reconnect handling</div>
        <div class="who"><span class="fx-tag ai">AI</span>builder</div>
        <div class="who"><span class="fx-tag tool">Tool</span>Gaori <span class="run">Test running</span></div></div>
      <div class="card"><div class="f">docs/api.md</div><div class="t">Update the API docs</div>
        <div class="who"><span class="fx-tag ai">AI</span>writer</div>
        <div class="who"><span class="fx-tag tool">Tool</span>Mulgae <span class="run">In review</span></div></div>
    </div>
    <div class="col">
      <h4><span class="st" style="background:var(--amber)"></span>Awaiting approval</h4>
      <div class="card hot"><div class="f">policy/refund.md</div><div class="t">Refund policy change proposal</div>
        <div class="diff"><div class="m"><b>−</b>Within 7 days of purchase</div><div class="p"><b>+</b>Within 14 days of purchase</div></div>
        <div class="who"><span class="fx-tag ai">AI</span>planner proposal</div>
        <div class="who"><span class="fx-tag human">Human</span>Approval needed</div>
        <div class="acts"><span class="btn go">Approve</span><span class="btn">Reject</span></div></div>
    </div>
    <div class="col">
      <h4><span class="st" style="background:var(--teal)"></span>Done</h4>
      <div class="card"><div class="f">tasks/login.md</div><div class="t">Fix the login error</div>
        <div class="who"><span class="fx-tag ai">AI</span>builder</div>
        <div class="who"><span class="fx-tag tool">Tool</span><span class="ok">Test ✓ Review ✓</span></div>
        <div class="who"><span class="fx-tag human">Human</span>Approved ✓</div></div>
      <div class="card"><div class="f">index</div><div class="t">Update the search index</div>
        <div class="who"><span class="fx-tag tool">Tool</span>doksuri CLI <span class="ok">✓</span></div></div>
    </div>
  </div>
  <div class="sync"><i></i>Local <span class="mono">Markdown</span> ↔ server, in sync</div>
</div>

<div class="chat fx-panel d-only">
  <div class="ch"><span class="av"><i></i></span><div><b>Root Kernel AI</b><span>Answers from this board</span></div></div>
  <div class="log">
    <div class="me">What is in progress right now?</div>
    <div class="ai"><span class="who">Root Kernel AI</span>Three AI&nbsp;Agents are at work. builder is building <span class="ref">session reconnect handling</span>, and Gaori runs the tests. The <span class="ref h">refund policy change</span> waits for a person to approve it.</div>
    <div class="me">Can’t the AI just change it?</div>
    <div class="ai"><span class="who">Root Kernel AI</span>Agents read and comment right away. An important change, such as a policy, goes up as a proposal and takes effect only when a person approves it.<br><span class="btn go">Try approving →</span></div>
  </div>
  <div class="sug"><span class="chip">Could our team use this?</span></div>
</div>
<p class="under hint d-only">An example screen. Doksuri is in development.</p></div></div>

<div class="m-only mchat fx-panel">
  <div class="ch"><span class="av"><i></i></span><div><b>Root Kernel AI</b><span>Answers from an example Doksuri project</span></div></div>
  <div class="log">
    <div class="me">What is in progress right now?</div>
    <div class="ai"><span class="who">Root Kernel AI</span>Three AI&nbsp;Agents are at work. Tools do the fixed work, and people approve the important changes.
      <div class="mb">
        <div class="h"><span class="fx-demo" style="height:18px;padding:0 5px;font-size:10px">Example</span>Doksuri · Markdown-native</div>
        <div class="r"><div><span class="t">Session reconnect handling</span><span class="s">In progress · builder · Gaori test</span></div><span class="fx-tag ai">AI</span></div>
        <div class="r hot"><div><span class="t">Refund policy change proposal</span><span class="s">Awaiting approval · planner proposal</span></div><span class="btn go" style="height:24px">Approve</span></div>
        <div class="r"><div><span class="t">Update the search index</span><span class="s">Done · doksuri CLI</span></div><span class="fx-tag tool">Tool</span></div>
      </div>
    </div>
  </div>
  <div class="sug"><span class="chip">Can’t the AI just change it?</span><span class="chip">Could our team use this?</span></div>
</div>
<p class="m-only hint mhint">An example screen. Doksuri is in development.</p>
</div>`;
export const crop = {"t":[504,146,1382,704]};
export function run(env) {
  const { sr, host, still: STILL_, narrow: NARROW_, scale: SCALE_ = () => 1 } = env;
  const W_ = globalThis, D_ = W_.document;
  const t_ = new Set(), i_ = new Set(), r_ = new Set(), o_ = [], off_ = [];
  const setTimeout = (f, ms, ...a) => { const id = W_.setTimeout(() => { t_.delete(id); f(...a); }, ms); t_.add(id); return id; };
  const clearTimeout = (id) => { W_.clearTimeout(id); t_.delete(id); };
  const setInterval = (f, ms, ...a) => { const id = W_.setInterval(f, ms, ...a); i_.add(id); return id; };
  const clearInterval = (id) => { W_.clearInterval(id); i_.delete(id); };
  const requestAnimationFrame = (f) => { const id = W_.requestAnimationFrame((ts) => { r_.delete(id); f(ts); }); r_.add(id); return id; };
  const cancelAnimationFrame = (id) => { W_.cancelAnimationFrame(id); r_.delete(id); };
  const addEventListener = (t, f, o) => { W_.addEventListener(t, f, o); off_.push(() => W_.removeEventListener(t, f, o)); };
  const matchMedia = (q) => (/max-width:\s*760px/.test(q) ? { matches: NARROW_ } : /prefers-reduced-motion/.test(q) ? { matches: STILL_ } : W_.matchMedia(q));
  const location = { search: STILL_ ? '?still' : '' };
  // a visual shown as a crop (.visw clips it) is "in view" by what the crop shows, not by its whole design space
  const IntersectionObserver = class extends W_.IntersectionObserver { constructor(cb, o) { super(cb, o); o_.push(this); } observe(t) { return super.observe(t?.closest?.('.visw') || t); } };
  const ResizeObserver = class extends W_.ResizeObserver { constructor(cb) { super(cb); o_.push(this); } };
  const document = {
    getElementById: (id) => sr.getElementById(id),
    querySelector: (s) => sr.querySelector(s),
    querySelectorAll: (s) => sr.querySelectorAll(s),
    documentElement: host, body: host,
    createElement: (t, o) => D_.createElement(t, o), createElementNS: (n, t) => D_.createElementNS(n, t),
    createTextNode: (t) => D_.createTextNode(t), createDocumentFragment: () => D_.createDocumentFragment(),
    createTreeWalker: (...a) => D_.createTreeWalker(...a),
    get fonts() { return D_.fonts; }, get hidden() { return D_.hidden; }, get timeline() { return D_.timeline; },
  };


// Motion and interaction (MOTION.md §3): the board is alive, and the decision is the visitor's.
// The markup above IS the approved still. Still mode leaves it untouched; the intro rebuilds an earlier
// moment of the same board and plays forward until the DOM is that still again. Nothing ever auto-approves.
(() => {
  const html = document.documentElement;
  const STILL = html.classList.contains('still');
  const M = STILL ? 0 : 1;                       // every duration and wait is scaled by this
  const MOB = matchMedia('(max-width: 760px)').matches;
  const EASE = 'cubic-bezier(.2,.7,.2,1)';
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const wait = (ms) => new Promise((res) => setTimeout(res, ms * M));
  const anim = (el, kf, o = {}) => el.animate(kf, { easing: EASE, ...o, duration: (o.duration ?? 600) * M, delay: (o.delay ?? 0) * M });
  const fadeUp = (el, o = {}) => anim(el, [{ opacity: 0, transform: `translateY(${o.dy ?? 10}px)` }, { opacity: 1, transform: 'none' }], { fill: 'backwards', ...o });
  const shown = (el) => getComputedStyle(el).display !== 'none';

  // the only lines this scene says (MOTION.md §3 + the still)
  const T = {
    q1: 'What is in progress right now?',
    q2: 'Can’t the AI just change it?',
    qTool: 'What do the Tools do?',
    qTeam: 'Could our team use this?',
    aTool: 'Tools do the work where the same input must give the same result, such as search, tests and sync. AI is used only where judgment is needed.',
    aTeam: 'Root Kernel designs the AI&nbsp;Agents, the Tools and the human approval steps together, around the way your team works.',
    aDone: 'Approval recorded. Who approved it, and when, is kept with it.',
    link: 'See AI transformation (AX) →',
    mDone: 'Done · human approval',
  };
  const WHO = '<span class="who">Root Kernel AI</span>';
  const STAMP = '<svg viewBox="0 0 38.5 57" aria-hidden="true"><path d="M0,0 L38.5,24 L38.5,33 L0,57 L0,44 L25.5,28.5 L0,13 Z"/></svg><i class="ring"></i>';

  // answers kept from the still itself, so a replayed conversation ends as the same DOM
  const dAis = $$('.chat .log .ai'), mAis = $$('.mchat .log .ai');
  const TPL = { d1: dAis[0].innerHTML, d2: dAis[1].innerHTML, m1: mAis[0].innerHTML };

  const state = { approved: false, asked: new Set(), introDone: false };
  const queue = () => { let tail = Promise.resolve(); return (fn) => (tail = tail.then(fn).catch((e) => console.error(e))); };
  const chatQ = queue();   // chat steps never interleave
  const boardQ = queue();  // board moves never overlap (FLIP needs quiet rects)

  const root = MOB ? $('.mchat') : $('.chat');
  const log = $('.log', root), sug = $('.sug', root);
  // the log stays pinned to its newest line, also when the chip bar wraps or the mobile panel grows
  if ('ResizeObserver' in window) new ResizeObserver(() => pin()).observe(log);

  // ---------------- chat machinery ----------------
  function pin() {
    requestAnimationFrame(() => {
      if (log.scrollHeight - log.clientHeight > 1) {
        log.classList.add('scrolled');
        log.scrollTo({ top: log.scrollHeight, behavior: M ? 'smooth' : 'auto' });
      }
    });
  }
  function bubble(text) {
    const d = document.createElement('div'); d.className = 'me'; d.textContent = text;
    log.appendChild(d); pin();
    anim(d, [{ opacity: 0, transform: 'translateY(8px)' }, { opacity: 1, transform: 'none' }], { duration: 320 });
    return d;
  }
  async function typing(ms = 700) {
    const t = document.createElement('div'); t.className = 'ai';
    t.innerHTML = WHO + '<span class="dots"><i></i><i></i><i></i></span>';
    log.appendChild(t); pin();
    anim(t, [{ opacity: 0 }, { opacity: 1 }], { duration: 200 });
    await wait(ms); t.remove();
  }
  function wrapWords(a) {
    const nodes = [], out = [];
    const tw = document.createTreeWalker(a, NodeFilter.SHOW_TEXT, {
      acceptNode: (n) => (n.parentElement.closest('.who, .btn, .lnk, .mb') ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT),
    });
    while (tw.nextNode()) nodes.push(tw.currentNode);
    for (const n of nodes) {
      const frag = document.createDocumentFragment();
      for (const part of n.textContent.split(/([ \t\n\r]+)/)) {
        if (!part) continue;
        if (/^[ \t\n\r]+$/.test(part)) { frag.appendChild(document.createTextNode(part)); continue; }
        const s = document.createElement('span'); s.className = 'w'; s.textContent = part;
        frag.appendChild(s); out.push(s);
      }
      n.replaceWith(frag);
    }
    return out;
  }
  // streams an answer word by word; the whole block is laid out first, so the log never jumps line by line
  async function answer(inner, { onRef, reveal, prepare } = {}) {
    const a = document.createElement('div'); a.className = 'ai'; a.innerHTML = inner;
    if (prepare) prepare(a);
    const extras = $$(':scope > .btn, :scope > .lnk, :scope > .mb', a);
    extras.forEach((x) => (x.style.opacity = '0'));
    const words = wrapWords(a);
    log.appendChild(a); pin();
    for (const w of words) {
      w.classList.add('on');
      const ref = w.closest('.ref');
      if (ref && onRef && !ref.__hit) { ref.__hit = true; onRef(ref); }
      await wait(45);
    }
    if (reveal) await reveal(a, extras);
    else for (const x of extras) { x.style.opacity = ''; fadeUp(x, { dy: 4, duration: 320 }); await wait(120); }
    await wait(170);
    for (const w of words) w.replaceWith(document.createTextNode(w.textContent));
    a.normalize();
    return a;
  }
  function addChip(text, animate = true) {
    const c = document.createElement('span'); c.className = 'chip'; c.textContent = text;
    sug.appendChild(c);
    if (animate) fadeUp(c, { dy: 6, duration: 380 });
    return c;
  }
  async function setChips(list) {
    $$('.chip', sug).forEach((c) => c.remove());
    for (const q of list) { addChip(q); await wait(110); }
  }
  async function pressChip(chip) {
    if (!chip || !chip.isConnected) return;
    anim(chip, [{ background: 'rgba(16,196,190,.06)' }, { background: 'rgba(16,196,190,.3)' }], { duration: 150, fill: 'forwards' });
    await wait(160);
    await anim(chip, [{ opacity: 1, transform: 'none' }, { opacity: 0, transform: 'translateY(-6px)' }], { duration: 200, fill: 'forwards' }).finished;
    chip.remove();
  }
  const chipFor = (q) => $$('.chip', sug).find((c) => c.textContent.trim() === q);
  async function ask(q, respond, chip) {
    state.asked.add(q);
    await pressChip(chip || chipFor(q));
    bubble(q);
    await wait(300);
    await typing(700);
    await respond();
  }

  // ---------------- shared bits of the board ----------------
  const snap = (els) => new Map(els.map((e) => [e, e.getBoundingClientRect()]));
  function flip(before, els, dur = 480) {
    return Promise.all(els.map((e) => {
      const a = before.get(e); if (!a || !e.isConnected) return null;
      const b = e.getBoundingClientRect(), dx = (a.left - b.left) / SCALE_(), dy = (a.top - b.top) / SCALE_();
      if (Math.abs(dx) < .5 && Math.abs(dy) < .5) return null;
      return anim(e, [{ transform: `translate(${dx}px, ${dy}px)` }, { transform: 'none' }], { duration: dur }).finished;
    }).filter(Boolean));
  }
  async function grow(el, mutate, dur = 380) {
    const h0 = el.getBoundingClientRect().height / SCALE_(); mutate(); const h1 = el.getBoundingClientRect().height / SCALE_();
    el.style.overflow = 'hidden';
    await anim(el, [{ height: h0 + 'px' }, { height: h1 + 'px' }], { duration: dur }).finished;
    el.style.overflow = '';
  }
  async function collapse(el, dur = 260) {
    el.style.overflow = 'hidden';
    const h = el.getBoundingClientRect().height / SCALE_(), mt = getComputedStyle(el).marginTop;
    await anim(el, [{ height: h + 'px', marginTop: mt, opacity: 1 }, { height: '0px', marginTop: '0px', opacity: 0 }], { duration: dur, fill: 'forwards' }).finished;
    el.remove();
  }
  const glowKF = (rgb, spread = 12) => [
    { boxShadow: `0 0 0 0 rgba(${rgb},0)` },
    { boxShadow: `0 0 ${spread}px 1px rgba(${rgb},.75)`, offset: .4 },
    { boxShadow: `0 0 0 0 rgba(${rgb},0)` },
  ];
  function glowTools() {
    const tags = MOB ? $$('.mchat .fx-tag.tool') : $$('.board .fx-tag.tool, .key .fx-tag.tool');
    tags.forEach((t, i) => anim(t, [
      { boxShadow: '0 0 0 0 rgba(16,196,190,0)', background: 'rgba(16,196,190,0)', borderColor: 'rgba(16,196,190,.42)', color: '#63DDD7' },
      { boxShadow: '0 0 16px 2px rgba(16,196,190,.85)', background: 'rgba(16,196,190,.22)', borderColor: '#8FF0EA', color: '#E8FFFD', offset: .35 },
      { boxShadow: '0 0 0 0 rgba(16,196,190,0)', background: 'rgba(16,196,190,0)', borderColor: 'rgba(16,196,190,.42)', color: '#63DDD7' },
    ], { duration: 1600, delay: i * 80 }));
  }
  // the stamp: > slams down, the host gives a little, a warm ring bursts at impact
  async function landSeal(seal, host) {
    const land = seal.animate([
      { opacity: 0, transform: 'scale(1.6)', easing: 'cubic-bezier(.55,0,1,.45)' },
      { opacity: 1, transform: 'scale(.92)', offset: .78, easing: 'ease-out' },
      { opacity: 1, transform: 'scale(1)' },
    ], { duration: 380 * M, easing: 'linear' });
    anim($('.ring', seal), [{ opacity: .95, transform: 'scale(1)' }, { opacity: 0, transform: 'scale(2.7)' }], { duration: 680, delay: 296 });
    if (host) anim(host, [{ transform: 'none' }, { transform: 'scale(.985)', offset: .45 }, { transform: 'none' }], { duration: 260, delay: 280, easing: 'ease-out' });
    await land.finished;
  }
  const makeSeal = () => { const s = document.createElement('span'); s.className = 'seal'; s.innerHTML = STAMP; return s; };

  // waiting for the human: the approve buttons breathe together, never bounce
  let waiting = [], waitT0 = null;
  const WAIT_KF = [
    { boxShadow: '0 0 0 0 rgba(255,194,133,.55)' },
    { boxShadow: '0 0 0 7px rgba(255,194,133,0)', offset: .45 },
    { boxShadow: '0 0 0 0 rgba(255,194,133,0)' },
  ];
  const HUMAN_KF = [
    { boxShadow: '0 0 0 0 rgba(255,194,133,0)' },
    { boxShadow: '0 0 9px 1px rgba(255,194,133,.55)', offset: .45 },
    { boxShadow: '0 0 0 0 rgba(255,194,133,0)' },
  ];
  function addWaiting(el, kf = WAIT_KF) {
    if (!el || STILL || state.approved) return;
    const a = el.animate(kf, { duration: 2500, iterations: Infinity, easing: 'ease-out' });
    if (waitT0 === null) waitT0 = document.timeline.currentTime;
    a.startTime = waitT0;
    waiting.push(a);
  }
  function stopWaiting() { waiting.forEach((a) => a.cancel()); waiting = []; waitT0 = null; }

  // ---------------- desktop ----------------
  function desktop() {
    const board = $('.board'), chat = $('.chat');
    const [cIn, cWait, cDone] = $$('.board .col');
    const cards = { session: cIn.children[1], api: cIn.children[2], refund: cWait.children[1], login: cDone.children[1], index: cDone.children[2] };
    const allCards = () => $$('.board .card');
    const humanRow = $$('.who', cards.refund)[1];
    let gaoriRow, mulgaeRow, idxMark;
    let boardEvents = Promise.resolve();   // the intro's live events; the approval's FLIP waits for quiet rects

    function syncPulse(dir = 1) {
      const s = $('.board .sync'), d = $('i', s);
      anim(d, [{ transform: 'scale(1)' }, { transform: 'scale(1.9)', boxShadow: '0 0 14px #63DDD7', offset: .35 }, { transform: 'scale(1)' }], { duration: 900 });
      anim(s, [{ color: 'rgba(237,233,231,.6)' }, { color: 'rgba(191,243,240,.95)', offset: .3 }, { color: 'rgba(237,233,231,.6)' }], { duration: 1200 });
      const pk = document.createElement('i'); pk.className = 'pk'; s.appendChild(pk);
      const W = s.clientWidth, a = dir > 0 ? 10 : W - 56, b = dir > 0 ? W - 56 : 10, f = dir > 0 ? '' : ' scaleX(-1)';
      const at = (t) => a + (b - a) * t;
      anim(pk, [
        { opacity: 0, transform: `translateX(${at(0)}px)${f}` },
        { opacity: 1, transform: `translateX(${at(.15)}px)${f}`, offset: .15 },
        { opacity: 1, transform: `translateX(${at(.8)}px)${f}`, offset: .8 },
        { opacity: 0, transform: `translateX(${at(1)}px)${f}` },
      ], { duration: 1150, easing: 'cubic-bezier(.45,0,.35,1)' }).finished.then(() => pk.remove());
    }
    function pulseCard(card, warm) {
      const rgb = warm ? '255,194,133' : '99,221,215';
      const rest = card.classList.contains('hot') ? '0 0 0 1px rgba(244,215,184,.18), 0 0 22px rgba(255,194,133,.12)' : '0 0 0 0 rgba(0,0,0,0), 0 0 0 rgba(0,0,0,0)';
      anim(card, [{ boxShadow: rest }, { boxShadow: `0 0 0 1.5px rgba(${rgb},.85), 0 0 26px rgba(${rgb},.34)`, offset: .35 }, { boxShadow: rest }], { duration: 1300 });
    }
    const refHit = (ref) => pulseCard(ref.classList.contains('h') ? cards.refund : cards.session, ref.classList.contains('h'));
    function presence() {
      $$('.board .ag').filter((ag) => $('.fx-tag.ai', ag)).forEach((ag, i) => {
        const d = document.createElement('i'); d.className = 'pd'; ag.appendChild(d);
        anim(d, [{ opacity: 0, transform: 'scale(.3)' }, { opacity: 1, transform: 'none' }], { duration: 420, delay: i * 120, fill: 'backwards' });
        d.animate([{ opacity: 1 }, { opacity: .38 }, { opacity: 1 }], { duration: 2600, delay: 600 + i * 420, iterations: Infinity, easing: 'ease-in-out' });
      });
    }
    function flarePresence() {
      const ds = $$('.board .ag .pd'); if (!ds.length) return;
      const d = ds[Math.floor(Math.random() * ds.length)];
      anim(d, [{ transform: 'none' }, { transform: 'scale(1.8)', boxShadow: '0 0 0 2px #041114, 0 0 14px rgba(191,243,240,.95)', offset: .35 }, { transform: 'none' }], { duration: 1000 });
    }

    // the earlier moment: index still running, no proposal yet, Tools not yet on the AI's work
    function rewind() {
      gaoriRow = cards.session.lastElementChild; gaoriRow.remove();
      mulgaeRow = cards.api.lastElementChild; mulgaeRow.remove();
      cards.api.remove(); cards.refund.remove();
      idxMark = $('.ok', cards.index); idxMark.className = 'run shim'; idxMark.textContent = 'Running';
      cIn.insertBefore(cards.index, cards.session);
      log.innerHTML = '';
      sug.innerHTML = ''; addChip(T.q1, false);
    }
    // E1 · Tool finishes deterministic work on its own and files it
    async function e1() {
      idxMark.className = 'ok'; idxMark.textContent = '✓';
      anim(idxMark, [{ color: '#F4FFFE', textShadow: '0 0 10px rgba(99,221,215,.95)' }, { color: '#63DDD7', textShadow: '0 0 0 rgba(0,0,0,0)' }], { duration: 700 });
      await wait(380);
      const all = allCards(), before = snap(all);
      cDone.appendChild(cards.index);
      cards.index.style.zIndex = 3;
      await flip(before, all, 520);
      cards.index.style.zIndex = '';
      syncPulse(1);
    }
    // E2 · an AI proposal arrives and waits for a human
    async function e2() {
      const c = cards.refund, m = $('.diff .m', c).lastChild, p = $('.diff .p', c).lastChild;
      const mt = m.textContent, pt = p.textContent;
      m.textContent = ''; p.textContent = '';
      const rows = [...$$('.who', c), $('.acts', c)];
      rows.forEach((r) => r.remove());
      cWait.appendChild(c);
      await anim(c, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'none' }], { duration: 560 }).finished;
      for (const [node, text] of [[m, mt], [p, pt]]) for (let i = 1; i <= text.length; i++) { node.textContent = text.slice(0, i); await wait(25); }
      for (const r of rows) await grow(c, () => { c.appendChild(r); fadeUp(r, { dy: 4, duration: 360 }); }, 240);
      anim($('.fx-tag.human', humanRow), HUMAN_KF, { duration: 1300 });
      syncPulse(-1);
    }
    // E3 · a Tool starts checking the AI's code
    async function e3() {
      await grow(cards.session, () => {
        $('.run', gaoriRow).classList.add('shim');
        cards.session.appendChild(gaoriRow);
        fadeUp(gaoriRow, { dy: 4, duration: 420 });
      });
    }
    // E4 · the writer's document enters the board, and a Tool reviews it
    async function e4() {
      cIn.appendChild(cards.api);
      await anim(cards.api, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'none' }], { duration: 560 }).finished;
      await wait(260);
      await grow(cards.api, () => {
        $('.run', mulgaeRow).classList.add('shim');
        cards.api.appendChild(mulgaeRow);
        fadeUp(mulgaeRow, { dy: 4, duration: 420 });
      });
      syncPulse(1);
    }

    function approve() {
      if (state.approved || !cWait.contains(cards.refund)) return;
      state.approved = true; stopWaiting();
      boardQ(async () => {
        const c = cards.refund;
        const seal = makeSeal(); c.appendChild(seal);
        await landSeal(seal, c);
        const txt = [...humanRow.childNodes].pop(); txt.textContent = 'Approved ✓';
        anim(humanRow, [{ color: '#F4D7B8' }, { color: 'rgba(237,233,231,.78)' }], { duration: 900 });
        $('.diff .m', c).classList.add('struck'); $('.diff .p', c).classList.add('lit');
        c.classList.remove('hot');
        anim(c, [{ boxShadow: '0 0 0 1px rgba(244,215,184,.6), 0 0 28px rgba(255,194,133,.3)' }, { boxShadow: '0 0 0 0 rgba(0,0,0,0), 0 0 0 rgba(0,0,0,0)' }], { duration: 900 });
        await collapse($('.acts', c));
        await wait(240);
        await boardEvents;
        const all = allCards(), before = snap(all);
        cDone.classList.add('over');
        cDone.insertBefore(c, cDone.children[1]);
        c.style.zIndex = 3;
        await flip(before, all, 580);
        c.style.zIndex = '';
        syncPulse(1);
      });
      chatQ(async () => {
        $$('.btn.go', log).forEach((b) => b.classList.add('off'));
        await wait(520);
        await typing(520);
        await answer(WHO + T.aDone);
        await setChips([T.qTool, T.qTeam].filter((q) => !state.asked.has(q)));
      });
      if (!STILL) startIdle();
    }

    const respond = {
      [T.q1]: () => answer(TPL.d1, { onRef: refHit }),
      [T.q2]: () => answer(TPL.d2),
      [T.qTool]: () => { glowTools(); return answer(WHO + T.aTool); },
      [T.qTeam]: () => answer(`${WHO}${T.aTeam}<br><span class="lnk">${T.link}</span>`),
    };
    let q1Promise = null, q1Tap;
    const q1Tapped = new Promise((r) => (q1Tap = r));
    const runQ1 = (chip) => (q1Promise ||= chatQ(() => ask(T.q1, respond[T.q1], chip)));
    function onChip(chip) {
      const q = chip.textContent.trim();
      if (state.asked.has(q) || !respond[q]) return;
      if (q === T.q1) { q1Tap(); runQ1(chip); return; }
      state.asked.add(q);
      chatQ(async () => { state.asked.delete(q); await ask(q, respond[q], chip); });
    }
    sug.addEventListener('click', (e) => { const c = e.target.closest('.chip'); if (c) onChip(c); });
    log.addEventListener('click', (e) => { if (e.target.closest('.btn.go')) approve(); });
    board.addEventListener('click', (e) => { if (e.target.closest('.acts .btn.go')) approve(); });

    async function intro() {
      rewind();
      window.__t0 = performance.now();
      $$('.msg > *').filter(shown).forEach((el, i) => fadeUp(el, { delay: i * 90, duration: 600 }));
      fadeUp(board, { delay: 300, duration: 650, dy: 12 });
      fadeUp(chat, { delay: 420, duration: 650, dy: 12 });
      anim($('.under'), [{ opacity: 0 }, { opacity: 1 }], { delay: 900, duration: 600, fill: 'backwards' });
      html.classList.remove('pre');
      setTimeout(presence, 800);
      setTimeout(() => boardQ(e1), 1000);
      const later = (ms, fn) => new Promise((r) => setTimeout(() => fn().then(r, r), ms));
      boardEvents = Promise.all([later(2000, e2), later(2700, e3), later(3900, e4)]);
      await Promise.race([wait(1600), q1Tapped]);
      await runQ1(chipFor(T.q1));
      if (!state.approved) {
        await wait(300);
        const c2 = state.asked.has(T.q2) ? null : addChip(T.q2);
        await wait(500);
        if (!state.approved) {
          if (!state.asked.has(T.q2)) { state.asked.add(T.q2); await chatQ(async () => { state.asked.delete(T.q2); await ask(T.q2, respond[T.q2], c2); }); }
          else await chatQ(() => {});
        }
        if (!state.approved) { await wait(250); if (!state.asked.has(T.qTeam) && !chipFor(T.qTeam)) addChip(T.qTeam); }
      }
      state.introDone = true;
      if (!state.approved) {
        addWaiting($('.acts .btn.go', cards.refund));
        $$('.btn.go', log).forEach((b) => addWaiting(b));
        addWaiting($('.fx-tag.human', humanRow), HUMAN_KF);
      }
    }

    let idleOn = false;
    function startIdle() {
      if (idleOn) return; idleOn = true;
      let k = 0;
      setInterval(() => { if (!document.hidden) (k++ % 2 ? flarePresence() : syncPulse(k % 4 === 1 ? 1 : -1)); }, 7000);
    }

    if (STILL) { state.asked = new Set([T.q1, T.q2]); state.introDone = true; return; }
    start(intro);
  }

  // ---------------- mobile ----------------
  function mobile() {
    const mchat = $('.mchat');
    const setMH = () => mchat.style.setProperty('--mh', Math.max(280, innerHeight - mchat.getBoundingClientRect().top - 44) + 'px');
    setMH(); addEventListener('resize', setMH);

    // the mini board inside the first answer: rows arrive one by one; the index job finishes on its own
    let mRows = [];
    const holdRows = (a) => { mRows = $$('.mb .r', a); mRows.forEach((r) => r.remove()); };
    async function revealBoard(a, extras) {
      const mb = extras[0];
      mb.style.opacity = ''; fadeUp(mb, { dy: 6, duration: 380 });
      await wait(240);
      const s = $('.s', mRows[2]), done = s.textContent;
      s.textContent = 'In progress · doksuri CLI';
      for (const [i, r] of mRows.entries()) {
        await grow(mb, () => {
          mb.appendChild(r);
          if (i === 1) anim(r, [{ opacity: 0, transform: 'translateY(-10px)' }, { opacity: 1, transform: 'none' }], { duration: 460 });
          else fadeUp(r, { dy: 6, duration: 420 });
        }, 300);
        pin();
        await wait(i === 2 ? 0 : 160);
      }
      await wait(620);
      s.textContent = done;
      anim(s, [{ color: '#8FF0EA' }, { color: 'rgba(237,233,231,.6)' }], { duration: 900 });
    }
    const revealInLog = async (el) => {
      const lr = log.getBoundingClientRect(), r = el.getBoundingClientRect();
      if (r.top < lr.top + 20 || r.bottom > lr.bottom - 8) { log.scrollBy({ top: r.top - lr.top - 36, behavior: M ? 'smooth' : 'auto' }); await wait(450); }
    };
    function approve() {
      const row = $('.mb .r.hot', log);
      if (state.approved || !row) return;
      state.approved = true; stopWaiting();
      chatQ(async () => {
        $$('.ai .btn.go', log).forEach((b) => b.classList.add('off'));
        await revealInLog(row);
        const seal = makeSeal(); $('.btn.go', row).replaceWith(seal);
        await landSeal(seal, row);
        row.classList.remove('hot');
        anim(row, [{ background: 'rgba(255,194,133,.16)' }, { background: 'rgba(7,26,31,1)' }], { duration: 900 });
        const s = $('.s', row); s.textContent = T.mDone;
        anim(s, [{ color: '#F4D7B8' }, { color: 'rgba(237,233,231,.6)' }], { duration: 1000 });
        await wait(700);
        await typing(520);
        await answer(WHO + T.aDone);
        await setChips([T.qTool, T.qTeam].filter((q) => !state.asked.has(q)));
      });
      if (!STILL) setInterval(() => {
        const t = $('.mb .fx-tag.ai', log); if (!document.hidden && t) anim(t, glowKF('191,243,240', 10), { duration: 1200 });
      }, 7000);
    }
    const respond = {
      [T.q1]: () => answer(TPL.m1, { prepare: holdRows, reveal: revealBoard }),
      [T.q2]: async () => { const a = await answer(TPL.d2); if (state.introDone) addWaiting($('.btn.go', a)); },
      [T.qTool]: () => { glowTools(); return answer(WHO + T.aTool); },
      [T.qTeam]: () => answer(`${WHO}${T.aTeam}<br><span class="lnk">${T.link}</span>`),
    };
    let q1Promise = null, q1Tap;
    const q1Tapped = new Promise((r) => (q1Tap = r));
    const runQ1 = (chip) => (q1Promise ||= chatQ(() => ask(T.q1, respond[T.q1], chip)));
    function onChip(chip) {
      const q = chip.textContent.trim();
      if (state.asked.has(q) || !respond[q]) return;
      if (q === T.q1) { q1Tap(); runQ1(chip); return; }
      if (q === T.q2 && state.approved) return;
      state.asked.add(q);
      chatQ(async () => { state.asked.delete(q); await ask(q, respond[q], chip); });
    }
    sug.addEventListener('click', (e) => { const c = e.target.closest('.chip'); if (c) onChip(c); });
    log.addEventListener('click', (e) => { if (e.target.closest('.btn.go')) approve(); });

    async function intro() {
      log.innerHTML = ''; sug.innerHTML = ''; addChip(T.q1, false);
      window.__t0 = performance.now();
      $$('.msg > *').filter(shown).forEach((el, i) => fadeUp(el, { delay: i * 90, duration: 600 }));
      fadeUp(mchat, { delay: 300, duration: 650, dy: 12 });
      anim($('.mhint'), [{ opacity: 0 }, { opacity: 1 }], { delay: 900, duration: 600, fill: 'backwards' });
      html.classList.remove('pre');
      await Promise.race([wait(1200), q1Tapped]);
      await runQ1(chipFor(T.q1));
      if (!state.approved) {
        await wait(250);
        for (const q of [T.q2, T.qTeam]) if (!state.asked.has(q) && !chipFor(q)) { addChip(q); await wait(120); }
      }
      state.introDone = true;
      if (!state.approved) {
        addWaiting($('.mb .r.hot .btn.go', log));
        $$('.ai .btn.go', log).forEach((b) => addWaiting(b));
      }
    }

    if (STILL) { state.asked = new Set([T.q1]); state.introDone = true; return; }
    start(intro);
  }

  // start when the scene is on screen (inside an iframe: when the iframe scrolls into view)
  function start(fn) {
    let went = false; const go = () => { if (!went) { went = true; fn(); } };
    const target = MOB ? $('.mchat') : $('.board');
    if (!('IntersectionObserver' in window)) return go();
    const io = new IntersectionObserver((es) => { if (es.some((e) => e.isIntersecting && e.intersectionRatio >= .35)) { io.disconnect(); go(); } }, { threshold: [0, .35, .6, 1] });
    io.observe(target);
  }

  MOB ? mobile() : desktop();
})();


  return () => {
    t_.forEach((id) => W_.clearTimeout(id)); i_.forEach((id) => W_.clearInterval(id)); r_.forEach((id) => W_.cancelAnimationFrame(id));
    o_.forEach((o) => o.disconnect()); off_.forEach((f) => f());
    // running animations are left alone: the site detaches the scene next, and cancelling them would reject
    // the `finished` promises the scene still awaits (AbortError)
  };
}
