// js/strengths/gear.js — 02 사내 시스템 · Built to mesh.
// Generated by lab/formats/port-scenes.mjs from the approved prototype lab/formats/live/gear/index.html.
// Change the prototype and regenerate (node lab/formats/port-scenes.mjs); do not edit this file by hand.
export const css = `:host {
  --ink: #EDE9E7; --ink2: rgba(237,233,231,.78); --ink3: rgba(237,233,231,.6); --ink4: rgba(237,233,231,.32);
  --teal: #10C4BE; --teal2: #63DDD7; --cyan: #BFF3F0; --warm: #F4D7B8; --amber: #FFC285; --red: #FF6B76;
  --bg: #01080a; --panel: #041114; --panel2: #071a1f; --panel3: #0c2329;
  --line: rgba(237,233,231,.12); --line2: rgba(237,233,231,.2); --line3: rgba(237,233,231,.32);
  --teal-a1: rgba(16,196,190,.10); --teal-a2: rgba(16,196,190,.22); --teal-a3: rgba(16,196,190,.42);
  --amber-a1: rgba(255,194,133,.09); --amber-a2: rgba(255,194,133,.34);
  --font: "Pretendard Variable", Pretendard, -apple-system, BlinkMacSystemFont, "Apple SD Gothic Neo", "Noto Sans KR", sans-serif;
  --mono: "IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, "Pretendard Variable", Pretendard, monospace;
}
*, *::before, *::after { box-sizing: border-box; }
:host {    color: var(--ink); font-family: var(--font); -webkit-font-smoothing: antialiased; letter-spacing: -.005em; }
.mono { font-family: var(--mono); letter-spacing: 0; }
.msg { position: absolute; z-index: 10; left: 72px; top: 196px; width: 440px; }
.kick { display: flex; align-items: baseline; gap: 7px; font: 400 13px var(--mono); color: var(--ink); }
.kick .area { font-family: var(--font); font-size: 13.5px; color: var(--teal); }
.hook { margin: 20px 0 0; font-size: 50px; line-height: 1.06; font-weight: 600; letter-spacing: -.03em; }
.lede { margin: 26px 0 0; font-size: 17.5px; line-height: 1.72; font-weight: 500; word-break: keep-all; }
.more { display: inline-flex; gap: 8px; margin-top: 30px; padding-bottom: 4px; font-size: 14px; color: var(--ink2); border-bottom: 1px solid var(--line3); }
.hint { font-size: 12.5px; color: var(--ink3); }
.fx-tag { display: inline-flex; align-items: center; height: 18px; padding: 0 5px; border: 1px solid var(--line2); border-radius: 4px; font: 500 11px/1 var(--mono); letter-spacing: .03em; color: var(--ink3); white-space: nowrap; }
.fx-tag.tool { color: var(--teal2); border-color: var(--teal-a3); }
.fx-tag.ai { color: var(--cyan); border-color: rgba(191,243,240,.35); }
.fx-tag.human { color: var(--warm); border-color: rgba(244,215,184,.45); }
.fx-demo { display: inline-flex; align-items: center; height: 22px; padding: 0 7px; border-radius: 5px; border: 1px solid var(--amber-a2); font: 500 11px var(--mono); color: var(--amber); letter-spacing: .02em; }
.fx-panel { background: var(--panel); border: 1px solid var(--line); border-radius: 14px; }
.m-only { display: none; }
:host(.m) .msg { position: relative; left: auto; top: auto; width: auto; padding: 84px 20px 0; }
:host(.m) .kick { font-size: 12px; }
:host(.m) .kick .area { font-size: 12.5px; }
:host(.m) .hook { margin-top: 12px; font-size: 31px; line-height: 1.12; }
:host(.m) .lede { margin-top: 14px; font-size: 14.5px; line-height: 1.62; }
:host(.m) .more { display: none; }
:host(.m) .d-only { display: none !important; }
:host(.m) .m-only { display: block; }
.stage { position: absolute; left: 0; top: 0; width: 1440px; height: 900px; z-index: 5; }
.stage svg { position: absolute; inset: 0; overflow: visible; }
.stage .gear { cursor: pointer; }
.stage svg .pk, .stage svg .sparks, .stage svg .lead, .stage svg .lead-dot, .stage svg .arw-a, .stage svg .arw-h, .mstage svg .pk, .mstage svg .sparks { pointer-events: none; }
:host(.still) * { transition: none !important; }
.glab { position: absolute; font: 500 11.5px var(--mono); color: var(--teal2); letter-spacing: .04em; white-space: nowrap; }
.glab span { font-family: var(--font); font-weight: 500; color: var(--ink3); letter-spacing: 0; margin-left: 6px; }
.call { position: absolute; width: 262px; padding: 14px 16px 14px; }
.call h3 { margin: 0; font-size: 15px; font-weight: 600; display: flex; flex-wrap: wrap; align-items: baseline; gap: 2px 8px; }
.call h3 .n { white-space: nowrap; }
.call h3 .s { font: 400 11.5px var(--mono); color: var(--teal2); }
.call h3 .dv { margin-left: auto; display: inline-flex; align-items: center; gap: 5px; font-size: 11.5px; font-weight: 500; color: var(--amber); white-space: nowrap; }
.call p { margin: 8px 0 0; font-size: 13.5px; line-height: 1.55; color: var(--ink); word-break: keep-all; }
.call p.b { margin-top: 10px; padding-top: 10px; border-top: 1px solid var(--line); color: var(--ink2); font-size: 13px; }
.call p.b b { color: var(--teal2); font-weight: 500; }
.legend { margin: 34px 0 0; padding: 0; list-style: none; border-top: 1px solid var(--line); }
.legend li { display: grid; grid-template-columns: 58px 1fr; gap: 10px; padding: 9px 0; border-bottom: 1px solid var(--line); font-size: 13px; color: var(--ink2); }
.legend li b { font-weight: 500; color: var(--ink); }
.legend li i { font-style: normal; color: var(--amber); }
.legend .dev { display: flex; align-items: center; gap: 7px; margin-top: 10px; font-size: 12px; color: var(--ink3); }
.dot { display: inline-block; width: 6px; height: 6px; border-radius: 50%; background: var(--amber); box-shadow: 0 0 6px rgba(255,194,133,.8); }
.dot.sm { width: 5px; height: 5px; margin: 0 0 6px 3px; vertical-align: middle; }
.legend li.note { display: flex; gap: 7px; align-items: center; border: 0; padding-top: 12px; font-size: 12.5px; color: var(--ink3); }
.legend li.note .sep { width: 1px; height: 11px; margin: 0 6px; background: var(--line2); }
.foot { position: absolute; white-space: nowrap; }
.mstage { position: relative; z-index: 5; margin: 10px 0 0; height: 196px; }
.mstage svg { width: 100%; height: 100%; overflow: visible; }
.groups { position: relative; z-index: 10; margin: 6px 20px 0; }
.grp { display: grid; grid-template-columns: 1fr 12px; gap: 10px; align-items: center; padding: 8px 0; border-top: 1px solid var(--line); cursor: pointer; -webkit-tap-highlight-color: transparent; }
.grp:last-child { border-bottom: 1px solid var(--line); }
.grp b { font-size: 14.5px; font-weight: 600; }
.grp b span { margin-left: 7px; font: 400 11px var(--mono); color: var(--teal2); }
.grp .m { display: block; margin-top: 2px; font-size: 12.5px; color: var(--ink2); }
.grp i { font-style: normal; color: var(--ink3); }
.grp .det { grid-column: 1 / 3; margin-top: 6px; padding: 9px 12px; border-radius: 10px; font-size: 12.5px; line-height: 1.48; overflow: hidden; }
.grp .det p { margin: 0 0 6px; }
.grp .det p:last-child { margin: 0; }
.grp .det b { font-size: 12.5px; color: var(--teal2); font-weight: 500; margin-right: 6px; }
.mhint { margin: 10px 20px 0; position: relative; z-index: 10; }
`;
export const html = `<div class="frame">
<section class="msg">
  <div class="kick"><span>02</span><span class="area">· 사내 시스템</span></div>
  <h2 class="hook">Built to mesh.</h2>
  <p class="lede">루트커널은 여러 도구가 맞물려 돌아가는 시스템 위에서 일합니다. 사내 시스템도 절차, 검증, 기록이 이렇게 맞물리도록 만듭니다.</p>
  <ul class="legend d-only" id="legend"></ul>
  <a class="more" href="#svcDetails"></a>
</section>

<div class="visw d-only"><div class="vis"><div class="stage" id="stage"></div></div></div>
<div class="m-only mstage" id="mstage"></div>
<div class="m-only groups" id="groups"></div>
<p class="m-only hint mhint">묶음을 누르면 도구의 역할을 볼 수 있습니다</p>
</div>`;
export const crop = {"t":[590,78,1382,834]};
export function run(env) {
  const { sr, host, still: STILL_, narrow: NARROW_, scale: SCALE_ = () => 1 } = env;
  const W_ = globalThis, D_ = W_.document;
  const t_ = new Set(), i_ = new Set(), r_ = new Set(), o_ = [], off_ = [];
  const setTimeout = (f, ms, ...a) => { const id = W_.setTimeout(() => { t_.delete(id); f(...a); }, ms); t_.add(id); return id; };
  const clearTimeout = (id) => { W_.clearTimeout(id); t_.delete(id); };
  const setInterval = (f, ms, ...a) => { const id = W_.setInterval(f, ms, ...a); i_.add(id); return id; };
  const clearInterval = (id) => { W_.clearInterval(id); i_.delete(id); };
  const requestAnimationFrame = (f) => { const id = W_.requestAnimationFrame((ts) => { r_.delete(id); f(ts); }); r_.add(id); return id; };
  const cancelAnimationFrame = (id) => { W_.cancelAnimationFrame(id); r_.delete(id); };
  const addEventListener = (t, f, o) => { W_.addEventListener(t, f, o); off_.push(() => W_.removeEventListener(t, f, o)); };
  const matchMedia = (q) => (/max-width:\s*760px/.test(q) ? { matches: NARROW_ } : /prefers-reduced-motion/.test(q) ? { matches: STILL_ } : W_.matchMedia(q));
  const location = { search: STILL_ ? '?still' : '' };
  // a visual shown as a crop (.visw clips it) is "in view" by what the crop shows, not by its whole design space
  const IntersectionObserver = class extends W_.IntersectionObserver { constructor(cb, o) { super(cb, o); o_.push(this); } observe(t) { return super.observe(t?.closest?.('.visw') || t); } };
  const ResizeObserver = class extends W_.ResizeObserver { constructor(cb) { super(cb); o_.push(this); } };
  const document = {
    getElementById: (id) => sr.getElementById(id),
    querySelector: (s) => sr.querySelector(s),
    querySelectorAll: (s) => sr.querySelectorAll(s),
    documentElement: host, body: host,
    createElement: (t, o) => D_.createElement(t, o), createElementNS: (n, t) => D_.createElementNS(n, t),
    createTextNode: (t) => D_.createTextNode(t), createDocumentFragment: () => D_.createDocumentFragment(),
    createTreeWalker: (...a) => D_.createTreeWalker(...a),
    get fonts() { return D_.fonts; }, get hidden() { return D_.hidden; }, get timeline() { return D_.timeline; },
  };


// Every tool here is a public repo under github.com/irootkernel. Roles: content.js TOOLS (site-approved)
// and the READMEs for the four tools not yet on the site. No counts anywhere.
// Motion: MOTION.md §2. `?still` or reduced motion renders the approved still (Podway selected) with no motion.
const STILL = new URLSearchParams(location.search).has('still') || matchMedia('(prefers-reduced-motion: reduce)').matches;
const MOBILE = matchMedia('(max-width: 760px)').matches;
const EASE = 'cubic-bezier(.2,.7,.2,1)';
if (STILL) document.body.classList.add('still');

const PITCH = 11; // circular pitch in px: every gear shares it, so the teeth really mesh
const G = {
  aquarium:  { name: 'Aquarium', tag: 'AI Harness', N: 66, grp: 'core',
    role: '여러 Tool을 한 작업 흐름으로 묶는 AI Harness입니다. 계획을 승인하기 전에는 아무것도 바꾸지 않습니다.' },
  podway:    { name: 'Podway', tag: 'Procedure', N: 42, grp: 'core', parent: 'aquarium', ang: 200,
    role: '작업 절차를 Gate와 rework 경로가 있는 FSM으로 설계하고, 작업 상태를 기록합니다.' },
  dispatch:  { name: 'Agent', name2: 'Dispatch', N: 32, grp: 'sync', parent: 'podway', ang: 252,
    role: '문서 저장소의 변경을 Deterministic한 계획과 receipt로 바꿔 AI Agent 작업으로 보냅니다.' },
  atn:       { name: 'Agent Turn', name2: 'Network', N: 32, grp: 'sync', parent: 'dispatch', ang: 196,
    role: '여러 AI Agent의 논의 진행 상태와 기록을 관리합니다.' },
  sanho:     { name: 'Sanho', ko: '산호', N: 26, grp: 'sync', parent: 'podway', ang: 140,
    role: '여러 저장소의 문서를 하나의 표준 문서 저장소와 동기화합니다.' },
  sorage:    { name: 'Sorage', ko: '소라게', N: 26, grp: 'sync', parent: 'sanho', ang: 96,
    role: 'AI 코딩 세션 사이에서 문서와 Review 의견을 넘깁니다.' },
  gaori:     { name: 'Gaori', ko: '가오리', N: 32, grp: 'verify', parent: 'aquarium', ang: -58,
    role: 'Test 명령을 실행하고 원본 로그와 실패 증거를 남깁니다.' },
  mulgae:    { name: 'Mulgae', ko: '물개', N: 29, grp: 'verify', parent: 'gaori', ang: -8,
    role: '여러 AI 모델에 Code review를 맡깁니다. 결과는 권고일 뿐 승인 권한이 없습니다.' },
  seongge:   { name: 'Seongge', ko: '성게', N: 27, grp: 'verify', parent: 'mulgae', ang: 52, dev: true,
    role: 'AI 스킬이 자신이 할 일과 하지 않을 일을 분명히 전하는지 검사합니다.' },
  dolgorae:  { name: 'Dolgorae', ko: '돌고래', N: 34, grp: 'run', parent: 'aquarium', ang: 34,
    role: '오래 실행되는 Codex 작업에 신원, 권한, 복구, 감사 기록을 붙입니다.' },
  gul:       { name: 'Gul', ko: '굴', N: 23, grp: 'run', parent: 'dolgorae', ang: -18, dev: true,
    role: '브라우저에서 개발 환경을 원격으로 조작하는 화면입니다. Codex 실행은 Dolgorae에 맡깁니다.' },
  haepari:   { name: 'Haepari', ko: '해파리', N: 26, grp: 'run', parent: 'dolgorae', ang: 96, dev: true,
    role: '명령 작업을 관리 대상으로 실행하고, 상태를 로컬 기록으로 남깁니다.' },
  gaebokchi: { name: 'Gaebokchi', ko: '개복치', N: 27, grp: 'run', parent: 'haepari', ang: 18,
    role: 'Codex·Grok·Claude 구독의 주간 사용량을 한 번에 확인합니다. 프롬프트는 보내지 않습니다.' },
};
// callout tag line (site TOOLS tags; the four new tools summarize their README in the same style)
const CTAG = { aquarium: 'AI Harness', podway: 'Procedure control', gaori: 'Test evidence', mulgae: 'Multi-model review',
  sanho: 'Doc sync', sorage: 'Cross-session review', dolgorae: 'Codex run control', dispatch: 'File → work',
  atn: 'Agent deliberation', seongge: 'Skill boundary check', haepari: 'Managed command jobs',
  gaebokchi: 'Weekly AI usage', gul: 'Remote operator UI' };
// "사내 시스템에서는 …" — only for the gears the tour visits
const BRIDGE = { podway: '결재·승인 흐름을 이렇게 상태와 전이로 설계합니다.',
  gaori: '업무 규칙마다 Test를 두고, 결과를 증거로 남깁니다.',
  dolgorae: '누가 무엇을 했는지 권한과 감사 기록으로 남깁니다.' };
const GROUPS = [
  { id: 'core', ko: '중심', en: 'Core', ids: ['aquarium', 'podway'] },
  { id: 'verify', ko: '검증', en: 'Verify', ids: ['gaori', 'mulgae', 'seongge'] },
  { id: 'sync', ko: '전달', en: 'Sync', ids: ['sanho', 'sorage', 'dispatch', 'atn'] },
  { id: 'run', ko: '실행', en: 'Run', ids: ['dolgorae', 'gul', 'haepari', 'gaebokchi'] },
];
const SEL = 'podway';
const TOUR = ['podway', 'gaori', 'dolgorae'];
const ROUTES = [['dispatch', 'podway', 'aquarium'], ['aquarium', 'dolgorae', 'haepari'],
  ['aquarium', 'gaori', 'mulgae', 'seongge'], ['podway', 'sanho', 'sorage']];
const label = (id) => G[id].name2 ? `${G[id].name} ${G[id].name2}` : G[id].name;

// ---- layout: each child sits on its parent's pitch circle; phases interleave the teeth ----
const TAU = Math.PI * 2, rad = (d) => d * Math.PI / 180, DEG = 180 / Math.PI;
const ADD = 0.30 * PITCH, DED = 0.36 * PITCH;
const order = Object.keys(G);
for (const id of order) {
  const g = G[id];
  g.r = g.N * PITCH / TAU; g.pa = TAU / g.N;
  if (!g.parent) { g.x = 0; g.y = 0; g.ph = 0; g.dir = 1; continue; }
  const p = G[g.parent], th = rad(g.ang), d = p.r + g.r;
  g.x = p.x + d * Math.cos(th); g.y = p.y + d * Math.sin(th);
  const u = (((th - p.ph) / p.pa) % 1 + 1) % 1;
  g.ph = th + Math.PI + (u + 0.5) * g.pa;
  g.dir = -p.dir;
}
// no two gears that are not meant to mesh may touch
const pairs = [];
for (let i = 0; i < order.length; i++) for (let j = i + 1; j < order.length; j++) {
  const a = G[order[i]], b = G[order[j]];
  if (a.parent === order[j] || b.parent === order[i]) continue;
  const gap = Math.hypot(a.x - b.x, a.y - b.y) - (a.r + ADD) - (b.r + ADD);
  if (gap < 8) pairs.push(`${order[i]}~${order[j]} gap ${gap.toFixed(1)}`);
}
if (pairs.length) console.error('gear collisions: ' + pairs.join(', '));
// the mesh as an undirected graph (for the glow wave)
const ADJ = Object.fromEntries(order.map((id) => [id, []]));
for (const id of order) if (G[id].parent) { ADJ[id].push(G[id].parent); ADJ[G[id].parent].push(id); }
const bfs = (from) => { const hop = { [from]: 0 }, q = [from]; while (q.length) { const c = q.shift(); for (const n of ADJ[c]) if (!(n in hop)) { hop[n] = hop[c] + 1; q.push(n); } } return hop; };

function bbox() {
  let x0 = 1e9, y0 = 1e9, x1 = -1e9, y1 = -1e9;
  for (const id of order) { const g = G[id], R = g.r + ADD; x0 = Math.min(x0, g.x - R); y0 = Math.min(y0, g.y - R); x1 = Math.max(x1, g.x + R); y1 = Math.max(y1, g.y + R); }
  return { x0, y0, x1, y1, w: x1 - x0, h: y1 - y0 };
}

function teeth(g) {
  const ro = g.r + ADD, rr = g.r - DED, pa = g.pa;
  const pt = (R, a) => `${(R * Math.cos(a)).toFixed(2)},${(R * Math.sin(a)).toFixed(2)}`;
  let d = `M ${pt(rr, -0.30 * pa)}`;
  for (let k = 0; k < g.N; k++) {
    const c = k * pa;
    d += ` L ${pt(ro, c - 0.13 * pa)} L ${pt(ro, c + 0.13 * pa)} L ${pt(rr, c + 0.30 * pa)} A ${rr.toFixed(2)} ${rr.toFixed(2)} 0 0 1 ${pt(rr, c + 0.70 * pa)}`;
  }
  return d + ' Z';
}
function windows(g, rh) {
  const n = g.r > 90 ? 6 : g.r > 48 ? 5 : 4, r1 = rh + 5, r2 = g.r - DED - 8;
  if (r2 - r1 < 6) return '';
  const sw = (g.r > 90 ? 13 : 8) / ((r1 + r2) / 2);
  const pt = (R, a) => `${(R * Math.cos(a)).toFixed(2)},${(R * Math.sin(a)).toFixed(2)}`;
  let d = '';
  for (let i = 0; i < n; i++) {
    const s = i * TAU / n + sw / 2, e = (i + 1) * TAU / n - sw / 2;
    d += `M ${pt(r1, s)} L ${pt(r2, s)} A ${r2} ${r2} 0 0 1 ${pt(r2, e)} L ${pt(r1, e)} A ${r1} ${r1} 0 0 0 ${pt(r1, s)} Z `;
  }
  return d;
}
const hubR = (g) => g.r > 90 ? 72 : Math.min(g.r * 0.64, g.r - DED - 9);
const strokeOf = (g, on) => on ? '#8FF0EA' : g.dev ? 'rgba(99,221,215,.55)' : 'rgba(99,221,215,.9)';

const LOGO = '<path d="M39.5,0 L0,24 L0,33 L39.5,57 L39.5,44 L14,28.5 L39.5,13 Z" fill="#10C4BE"/><rect x="66" y="50" width="52" height="9" fill="#10C4BE"/><path d="M144,0 L182.5,24 L182.5,33 L144,57 L144,44 L169.5,28.5 L144,13 Z" fill="#EDE9E7"/>';

// ---- the one rotation clock: angle_i = φ_i + dir_i · (N_root / N_i) · Θ ----
// Still frame: Θ where the approved still was captured (its WAAPI rotation had run ~1.5 s).
const THETA_STILL = 4.1;
const rotDeg = (g, theta) => g.ph * DEG + g.dir * (G.aquarium.N / g.N) * theta;

const defs = (uid, scale) => `<defs>
  <filter id="gl${uid}" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="${2.2 * scale}" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  <radialGradient id="hub${uid}"><stop offset="0" stop-color="#0c2329"/><stop offset="1" stop-color="#041114"/></radialGradient>
  <radialGradient id="pk${uid}"><stop offset="0" stop-color="#E8FFFD" stop-opacity="1"/><stop offset=".22" stop-color="#8FF0EA" stop-opacity=".55"/><stop offset=".55" stop-color="#10C4BE" stop-opacity=".16"/><stop offset="1" stop-color="#10C4BE" stop-opacity="0"/></radialGradient>
  <radialGradient id="sp${uid}"><stop offset="0" stop-color="#FFF8EE" stop-opacity="1"/><stop offset=".35" stop-color="#FFE3C4" stop-opacity=".55"/><stop offset="1" stop-color="#FFC285" stop-opacity="0"/></radialGradient>
</defs>`;

// ---- one renderer for both sizes: `labels` decides whether hub text is drawn ----
function mechanism({ ox, oy, scale = 1, labels = true, uid, theta }) {
  let body = '';
  // draw large gears first so small ones sit on top where their teeth interleave
  const ids = [...order].sort((a, b) => G[b].r - G[a].r);
  for (const id of ids) {
    const g = G[id], on = id === SEL, rh = hubR(g), stroke = strokeOf(g, on);
    const cx = ox + g.x * scale, cy = oy + g.y * scale;
    // labels keep the exact (unrounded) centre of the approved still: offset them by the rounding of the group translate
    const fx = cx - +cx.toFixed(1), fy = cy - +cy.toFixed(1), X = (v) => +(fx + v).toFixed(4), Y = (v) => +(fy + v).toFixed(4);
    let lab = '';
    if (labels) {
      if (id === 'aquarium') {
        const k = 0.36;
        lab = `<g class="lab" transform="translate(${X(-182.5 * k / 2)},${Y(-38)}) scale(${k})">${LOGO}</g>
          <text class="lab hn big" x="${X(0)}" y="${Y(14)}" text-anchor="middle">Aquarium</text>
          <text class="lab ht mono" x="${X(0)}" y="${Y(33)}" text-anchor="middle">AI Harness</text>`;
      } else {
        const two = !!g.name2, sub = g.ko || g.tag || '';
        const ny = two ? -3 : (sub ? -1 : 4);
        lab = `<text class="lab hn nm${on ? ' on' : ''}" x="${X(0)}" y="${Y(ny)}" text-anchor="middle">${g.name}</text>`;
        if (two) lab += `<text class="lab hn nm${on ? ' on' : ''}" x="${X(0)}" y="${Y(ny + 15)}" text-anchor="middle">${g.name2}</text>`;
        else if (sub) lab += `<text class="lab ht${g.tag ? ' mono' : ''}" x="${X(0)}" y="${Y(ny + 15)}" text-anchor="middle">${sub}</text>`;
      }
    } else if (id === 'aquarium') {
      const k = 0.2;
      lab = `<g class="lab" transform="translate(${X(-182.5 * k / 2)},${Y(-57 * k / 2)}) scale(${k})">${LOGO}</g>`;
    }
    body += `<g class="gear" data-id="${id}" transform="translate(${cx.toFixed(1)},${cy.toFixed(1)})"><g class="arr">
      <g transform="scale(${scale})">
        <g class="spin" data-id="${id}" transform="rotate(${rotDeg(g, theta).toFixed(3)})">
          <path class="tt" pathLength="1" d="${teeth(g)}" fill="#041114" fill-opacity=".93" stroke="${stroke}" stroke-width="${on ? 1.7 : 1.15}" vector-effect="non-scaling-stroke" filter="url(#gl${uid})"/>
          <circle class="rim" r="${(g.r - DED - 4).toFixed(1)}" fill="none" stroke="${stroke}" stroke-opacity=".45" stroke-width="1" vector-effect="non-scaling-stroke"/>
          <path class="win" d="${windows(g, rh)}" fill="#01080a" fill-opacity=".9" stroke="${stroke}" stroke-opacity=".38" stroke-width="1" vector-effect="non-scaling-stroke"/>
          <path class="fl" d="${teeth(g)}" fill="none" stroke="#D6FFFB" stroke-width="1.9" vector-effect="non-scaling-stroke" filter="url(#gl${uid})" opacity="0"/>
        </g>
        <circle class="hub" r="${rh.toFixed(1)}" fill="url(#hub${uid})" stroke="${stroke}" stroke-opacity="${on ? .9 : .5}" stroke-width="1" vector-effect="non-scaling-stroke"/>
        <circle class="hr" r="${rh.toFixed(1)}" fill="none" stroke="#BFF3F0" stroke-width="1.6" vector-effect="non-scaling-stroke" opacity="0"/>
        ${g.dev ? `<circle class="dv" cx="0" cy="${(-rh + 7).toFixed(1)}" r="2.6" fill="#FFC285"/>` : ''}
      </g>${lab}</g></g>`;
  }
  return body;
}

const TXT = `<style>
  .hn { font: 600 12.5px "Pretendard Variable", Pretendard, sans-serif; fill: #EDE9E7; transition: fill .4s; }
  .hn.big { font-size: 16px; } .hn.on { fill: #8FF0EA; }
  .ht { font: 400 10.5px "Pretendard Variable", Pretendard, sans-serif; fill: rgba(237,233,231,.6); }
  .ht.mono { font-family: "IBM Plex Mono", monospace; fill: #63DDD7; font-size: 10px; }
  .tt, .hub { transition: stroke .45s, stroke-width .45s, stroke-opacity .45s; }
</style>`;

// packet: halo + core + a short fading trail (drawn above every gear)
const packetMarkup = (uid, k) => `<g class="pk" opacity="0">
  ${[5, 4, 3, 2, 1].map((j) => `<circle class="tr" r="${((2.7 - j * 0.32) * k).toFixed(2)}" fill="#BFF3F0" opacity="${(0.72 - j * 0.12).toFixed(2)}"/>`).join('')}
  <circle class="ha" r="${(17 * k).toFixed(2)}" fill="url(#pk${uid})"/><circle class="co" r="${(2.9 * k).toFixed(2)}" fill="#F2FFFE"/></g>`;

// ---- instances (desktop + mobile share everything but scale and labels) ----
const INST = {};

(function desktop() {
  const bb = bbox(), TX = 968, TY = 480;
  const ox = TX - (bb.x0 + bb.w / 2), oy = TY - (bb.y0 + bb.h / 2);
  const theta = STILL ? THETA_STILL : 0;
  let svg = `<svg width="1440" height="900" viewBox="0 0 1440 900" aria-hidden="true">${TXT}${defs('d', 1)}<g class="gears">` + mechanism({ ox, oy, uid: 'd', theta }) + '</g>';
  // rotation cue on the drive gear (Podway): a thin arc with an arrowhead
  const p = G.podway, pcx = ox + p.x, pcy = oy + p.y, R = p.r + ADD + 10;
  const arc = (a0, a1) => {
    const s = [pcx + R * Math.cos(rad(a0)), pcy + R * Math.sin(rad(a0))], e = [pcx + R * Math.cos(rad(a1)), pcy + R * Math.sin(rad(a1))];
    const dir = p.dir > 0 ? 1 : 0; // clockwise on screen when dir > 0
    const tip = rad(a1), tx = -Math.sin(tip) * (p.dir > 0 ? 1 : -1), ty = Math.cos(tip) * (p.dir > 0 ? 1 : -1);
    const nx = Math.cos(tip), ny = Math.sin(tip);
    const h1 = [e[0] - tx * 7 + nx * 3.5, e[1] - ty * 7 + ny * 3.5], h2 = [e[0] - tx * 7 - nx * 3.5, e[1] - ty * 7 - ny * 3.5];
    return `<path class="arw-a" pathLength="1" d="M ${s[0]} ${s[1]} A ${R} ${R} 0 0 ${dir} ${e[0]} ${e[1]}" fill="none" stroke="#8FF0EA" stroke-width="1.3" stroke-linecap="round" opacity=".9"/>
      <path class="arw-h" d="M ${h1[0]} ${h1[1]} L ${e[0]} ${e[1]} L ${h2[0]} ${h2[1]}" fill="none" stroke="#8FF0EA" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>`;
  };
  svg += p.dir > 0 ? arc(150, 196) : arc(252, 206);
  // callout leader for the selected gear (Podway in the still)
  const lx = pcx + 14, ly0 = pcy + p.r + ADD + 4, cardTop = oy + G.aquarium.y + G.aquarium.r + ADD + 34;
  svg += `<path class="lead" pathLength="1" d="M ${lx} ${ly0} L ${lx} ${cardTop}" stroke="#63DDD7" stroke-width="1" opacity=".75" fill="none"/>
    <circle class="lead-dot" cx="${lx}" cy="${ly0}" r="3" fill="#8FF0EA"/>`;
  svg += `<g class="sparks"></g>${packetMarkup('d', 1)}</svg>`;
  let html = svg;
  const g = G[SEL];
  html += `<div class="call fx-panel" style="left:${lx - 44}px;top:${cardTop}px">
    <h3>${g.name}<span class="s">Procedure control</span></h3>
    <p>${g.role}</p>
    <p class="b"><b>사내 시스템에서는</b> 결재·승인 흐름을 이렇게 상태와 전이로 설계합니다.</p></div>`;
  // group labels, placed at the outer edge of each cluster
  const place = { verify: ['top', 0], sync: ['top', 0], run: ['bottom', 0], core: ['bottom', 0] };
  for (const gr of GROUPS) {
    if (gr.id === 'core') continue;
    let x0 = 1e9, y0 = 1e9, x1 = -1e9, y1 = -1e9;
    for (const id of gr.ids) { const q = G[id], R = q.r + ADD; x0 = Math.min(x0, ox + q.x - R); y0 = Math.min(y0, oy + q.y - R); x1 = Math.max(x1, ox + q.x + R); y1 = Math.max(y1, oy + q.y + R); }
    const top = place[gr.id][0] === 'top';
    const lx = gr.id === 'run' ? x1 - 150 : gr.id === 'verify' ? x1 - 140 : x0 + 4, ly = top ? y0 - 26 : y1 + 12;
    html += `<div class="glab" style="left:${lx}px;top:${ly}px">${gr.en}<span>${gr.ko}</span></div>`;
  }
  const stage = document.getElementById('stage');
  stage.innerHTML = html;

  document.getElementById('legend').innerHTML = GROUPS.map((gr) =>
    `<li><b>${gr.ko}</b><span>${gr.ids.map((id) => label(id) + (G[id].dev ? '<span class="dot sm"></span>' : '')).join(' · ')}</span></li>`).join('')
    + `<li class="note"><span class="dot"></span>개발 중<span class="sep"></span>톱니를 누르면 역할을 볼 수 있습니다</li>`;

  const pos = Object.fromEntries(order.map((id) => [id, { cx: ox + G[id].x, cy: oy + G[id].y, r: G[id].r, R: G[id].r + ADD }]));
  INST.d = { el: stage, svg: stage.querySelector('svg'), pos, scale: 1, uid: 'd',
    podwayLeader: { lx, ly0, cardTop, boxLeft: lx - 44 } };
})();

// ---- mobile: the same mechanism, smaller and unlabeled except the hub; groups as a list ----
(function mobile() {
  const bb = bbox(), W = 390, H = 196, s = Math.min((W - 24) / bb.w, (H - 8) / bb.h);
  const ox = W / 2 - (bb.x0 + bb.w / 2) * s, oy = H / 2 - (bb.y0 + bb.h / 2) * s;
  const theta = STILL ? THETA_STILL : 0;
  let svg = `<svg viewBox="0 0 ${W} ${H}" aria-hidden="true">${TXT}${defs('m', s)}<g class="gears">` + mechanism({ ox, oy, scale: s, labels: false, uid: 'm', theta }) + '</g>';
  svg += `<g class="sparks"></g>${packetMarkup('m', 0.62)}</svg>`;
  const mstage = document.getElementById('mstage');
  mstage.innerHTML = svg;
  const OPEN = 'core';
  document.getElementById('groups').innerHTML = GROUPS.map((gr) => `
    <div class="grp" data-g="${gr.id}"><div><b>${gr.ko}<span>${gr.en}</span></b><span class="m">${gr.ids.map(label).join(' · ')}</span></div><i>${gr.id === OPEN ? '⌄' : '›'}</i>
    ${gr.id === OPEN ? `<div class="det fx-panel">${gr.ids.map((id) => `<p><b>${label(id)}</b>${G[id].role}</p>`).join('')}</div>` : ''}</div>`).join('');
  const pos = Object.fromEntries(order.map((id) => [id, { cx: ox + G[id].x * s, cy: oy + G[id].y * s, r: G[id].r * s, R: (G[id].r + ADD) * s }]));
  INST.m = { el: mstage, svg: mstage.querySelector('svg'), pos, scale: s, uid: 'm', open: OPEN };
})();

// =====================================================================================
// motion
// =====================================================================================
const $ = (root, sel) => root.querySelector(sel), $$ = (root, sel) => [...root.querySelectorAll(sel)];
const gearEl = (inst, id) => $(inst.svg, `.gear[data-id="${id}"]`);
const smooth = (x) => x <= 0 ? 0 : x >= 1 ? 1 : x * x * (3 - 2 * x);

// set the final state as inline style, animate from `from` (no fill: the inline style is the end state)
function play(el, from, to, dur, opts = {}) {
  if (!el) return null;
  Object.assign(el.style, to);
  if (STILL) return null;
  const kf = [{ ...from }, { ...to }];
  return el.animate(kf, { duration: dur, easing: opts.easing || EASE, delay: opts.delay || 0, fill: opts.delay ? 'backwards' : 'none' });
}
function pulse(el, prop, peak, dur, easing = 'ease-out') {
  if (!el || STILL) return;
  el.animate([{ [prop]: 0 }, { [prop]: peak, offset: 0.28 }, { [prop]: 0 }], { duration: dur, easing });
}
function drawLine(el, dur, delay = 0) {
  if (!el) return;
  el.style.strokeDasharray = '1';
  el.style.strokeDashoffset = '0';
  if (STILL) return;
  el.animate([{ strokeDashoffset: 1 }, { strokeDashoffset: 0 }], { duration: dur, easing: EASE, delay, fill: 'backwards' });
}

// ---- selection (teeth stroke, hub ring, label colour) ----
function setBright(inst, id, on) {
  const g = G[id], el = gearEl(inst, id);
  const tt = $(el, '.tt'), hub = $(el, '.hub');
  tt.style.stroke = strokeOf(g, on); tt.style.strokeWidth = on ? '1.7' : '1.15';
  for (const c of [$(el, '.rim'), $(el, '.win'), hub]) c.style.stroke = strokeOf(g, on);
  hub.style.strokeOpacity = on ? '.9' : '.5';
  for (const t of $$(el, '.nm')) t.classList.toggle('on', on);
}

// ---- rotation clock ----
let theta = STILL ? THETA_STILL : 0; // root angle in degrees
const W_CRUISE = 360 / 140000;       // deg per ms: one root revolution per 140 s
const SPIN_RAMP = 1400;
let spinAt = Infinity;               // clock time when the drive starts
const spins = $$(document, '.spin').map((el) => ({ el, g: G[el.dataset.id] }));
function applyRotation() {
  for (const s of spins) s.el.setAttribute('transform', `rotate(${rotDeg(s.g, theta).toFixed(3)})`);
}
window.__gear = { theta: () => theta, N: Object.fromEntries(order.map((id) => [id, G[id].N])),
  pairs: order.filter((id) => G[id].parent).map((id) => [G[id].parent, id]),
  set: (th) => { theta = th; applyRotation(); } };

// ---- scheduler on the same clock (pauses with the page, never drifts from the rotation) ----
let clock = 0, running = false;
const queue = [];
const at = (t, fn) => { queue.push({ t, fn }); queue.sort((a, b) => a.t - b.t); };

// ---- packets riding the pitch circles, handed over at the contact points ----
function buildRoute(inst, ids) {
  const P = inst.pos, gs = ids.map((id) => P[id]);
  const contact = []; // pitch point between gear k and k+1
  for (let k = 0; k < gs.length - 1; k++) { const a = gs[k], b = gs[k + 1], t = a.r / (a.r + b.r); contact.push([a.cx + (b.cx - a.cx) * t, a.cy + (b.cy - a.cy) * t]); }
  const ang = (g, pt) => Math.atan2(pt[1] - g.cy, pt[0] - g.cx);
  const norm = (a) => ((a % TAU) + TAU) % TAU;
  const lead = 60 * inst.scale, tail = 60 * inst.scale;
  let best = null;
  for (const s0 of [1, -1]) {
    const segs = []; let s = s0, total = 0;
    { const g = gs[0], a1 = ang(g, contact[0]), sw = s * lead / g.r; segs.push({ id: ids[0], g, a0: a1 - sw, sw }); }
    for (let i = 1; i < gs.length - 1; i++) { s = -s; const g = gs[i], a0 = ang(g, contact[i - 1]), a1 = ang(g, contact[i]); segs.push({ id: ids[i], g, a0, sw: s * norm((a1 - a0) * s) }); }
    { s = -s; const g = gs[gs.length - 1], a0 = ang(g, contact[contact.length - 1]); segs.push({ id: ids[ids.length - 1], g, a0, sw: s * tail / g.r }); }
    for (const sg of segs) { sg.len = Math.abs(sg.sw) * sg.g.r; sg.from = total; total += sg.len; }
    if (!best || total < best.L) best = { segs, L: total };
  }
  return best;
}
function pointOn(route, d) {
  let sg = route.segs[route.segs.length - 1];
  for (const s of route.segs) if (d <= s.from + s.len) { sg = s; break; }
  const t = Math.max(0, Math.min(1, (d - sg.from) / sg.len)), a = sg.a0 + sg.sw * t;
  return [sg.g.cx + sg.g.r * Math.cos(a), sg.g.cy + sg.g.r * Math.sin(a)];
}
let packet = null; // { inst, route, t0, dur, lit }
const PACKET_MS_PER_PX = 1000 / 300; // desktop speed; mobile keeps the same durations
function launchPacket(inst, k) {
  const route = buildRoute(inst, ROUTES[k % ROUTES.length]);
  packet = { inst, route, t0: clock, dur: route.L / inst.scale * PACKET_MS_PER_PX, lit: -1 };
}
function updatePacket() {
  if (!packet) return;
  const { inst, route } = packet, pk = $(inst.svg, '.pk');
  const u = (clock - packet.t0) / packet.dur;
  if (u >= 1) { pk.setAttribute('opacity', '0'); packet = null; return; }
  const d = u * route.L;
  // light each gear's hub ring as the packet reaches it
  const seg = route.segs.findIndex((s) => d <= s.from + s.len);
  if (seg > packet.lit) { for (let i = packet.lit + 1; i <= seg; i++) pulse($(gearEl(inst, route.segs[i].id), '.hr'), 'opacity', 0.95, 700); packet.lit = seg; }
  const fade = Math.min(1, d / (26 * inst.scale), (route.L - d) / (40 * inst.scale));
  pk.setAttribute('opacity', Math.max(0, fade).toFixed(3));
  const [x, y] = pointOn(route, d);
  $(pk, '.ha').setAttribute('cx', x.toFixed(2)); $(pk, '.ha').setAttribute('cy', y.toFixed(2));
  $(pk, '.co').setAttribute('cx', x.toFixed(2)); $(pk, '.co').setAttribute('cy', y.toFixed(2));
  $$(pk, '.tr').forEach((c, i) => { const [tx, ty] = pointOn(route, Math.max(0, d - (5 - i) * 8 * inst.scale)); c.setAttribute('cx', tx.toFixed(2)); c.setAttribute('cy', ty.toFixed(2)); });
}

// ---- callout: one box, re-anchored per gear with a clean leader ----
const OBST_PAD = 6;
function segHitsCircle(x1, y1, x2, y2, cx, cy, r) {
  const dx = x2 - x1, dy = y2 - y1, L2 = dx * dx + dy * dy;
  const t = L2 ? Math.max(0, Math.min(1, ((cx - x1) * dx + (cy - y1) * dy) / L2)) : 0;
  return Math.hypot(x1 + dx * t - cx, y1 + dy * t - cy) < r;
}
function segHitsRect(x1, y1, x2, y2, r) { // axis-aligned segments only
  const minx = Math.min(x1, x2), maxx = Math.max(x1, x2), miny = Math.min(y1, y2), maxy = Math.max(y1, y2);
  return maxx > r.l && minx < r.r && maxy > r.t && miny < r.b;
}
function findLeader(target, box, rects) {
  const P = INST.d.pos, T = P[target];
  const clean = (pts) => {
    for (let i = 0; i < pts.length - 1; i++) {
      const [x1, y1] = pts[i], [x2, y2] = pts[i + 1];
      for (const id of order) {
        const q = P[id];
        if (id === target) { if (i < pts.length - 2 && segHitsCircle(x1, y1, x2, y2, q.cx, q.cy, q.R + 2)) return false; continue; }
        if (segHitsCircle(x1, y1, x2, y2, q.cx, q.cy, q.R + OBST_PAD)) return false;
      }
      for (const r of rects) if (segHitsRect(x1, y1, x2, y2, r)) return false;
      // never run back through the box itself (the first point sits on its edge)
      if (segHitsRect(x1, y1, x2, y2, { l: box.l + 1, r: box.r - 1, t: box.t + 1, b: box.b - 1 })) return false;
    }
    return true;
  };
  const rimY = (x, side) => T.cy + side * Math.sqrt(Math.max(0, (T.R + 4) ** 2 - (x - T.cx) ** 2));
  const rimX = (y, side) => T.cx + side * Math.sqrt(Math.max(0, (T.R + 4) ** 2 - (y - T.cy) ** 2));
  const cands = [];
  const reachX = (x) => Math.abs(x - T.cx) <= T.R - 10, reachY = (y) => Math.abs(y - T.cy) <= T.R - 10;
  // 0. straight horizontal from the box's left or right edge
  for (let y = box.t + 18; y <= box.b - 18; y += 4) if (reachY(y)) {
    if (T.cx > box.r) cands.push([[box.r, y], [rimX(y, -1), y]]);
    if (T.cx < box.l) cands.push([[box.l, y], [rimX(y, 1), y]]);
  }
  // 1. straight vertical from the box's top or bottom edge
  for (let x = box.l + 22; x <= box.r - 22; x += 4) if (reachX(x)) {
    if (T.cy < box.t) cands.push([[x, box.t], [x, rimY(x, 1)]]);
    if (T.cy > box.b) cands.push([[x, box.b], [x, rimY(x, -1)]]);
  }
  // 2. horizontal from a side, then vertical to the rim
  for (let y = box.t + 18; y <= box.b - 18; y += 6) for (const sx of [box.l, box.r]) {
    for (let x = T.cx - T.R + 10; x <= T.cx + T.R - 10; x += 4) {
      if (sx === box.l && x > box.l - 14) continue; if (sx === box.r && x < box.r + 14) continue;
      const side = T.cy > y ? -1 : 1, ey = rimY(x, side);
      if ((side < 0 && ey <= y + 8) || (side > 0 && ey >= y - 8)) continue;
      cands.push([[sx, y], [x, y], [x, ey]]);
    }
  }
  // 3. vertical from the top/bottom edge, then horizontal to the rim
  for (let x = box.l + 22; x <= box.r - 22; x += 6) for (const sy of [box.t, box.b]) {
    for (let y = T.cy - T.R + 10; y <= T.cy + T.R - 10; y += 4) {
      if (sy === box.t && y > box.t - 14) continue; if (sy === box.b && y < box.b + 14) continue;
      const side = T.cx > x ? -1 : 1, ex = rimX(y, side);
      if ((side < 0 && ex <= x + 8) || (side > 0 && ex >= x - 8)) continue;
      cands.push([[x, sy], [x, y], [ex, y]]);
    }
  }
  let best = null, bestScore = Infinity;
  for (const pts of cands) {
    let len = 0; for (let i = 0; i < pts.length - 1; i++) len += Math.hypot(pts[i + 1][0] - pts[i][0], pts[i + 1][1] - pts[i][1]);
    const score = len + (pts.length - 2) * 60;
    if (score < bestScore && clean(pts)) { best = pts; bestScore = score; }
  }
  return best ? best.slice().reverse() : null; // from the gear to the box
}
function calloutHTML(id) {
  const g = G[id];
  return `<h3><span class="n">${label(id)}</span><span class="s">${CTAG[id]}</span>${g.dev ? '<span class="dv"><span class="dot"></span>개발 중</span>' : ''}</h3>
    <p>${g.role}</p>${BRIDGE[id] ? `<p class="b"><b>사내 시스템에서는</b> ${BRIDGE[id]}</p>` : ''}`;
}
let selected = SEL, toured = true, callTimer = 0, introDone = STILL;
function select(id, { fromTour = false } = {}) {
  if (!fromTour) toured = false;
  if (id === selected) return;
  const inst = INST.d, prev = selected;
  selected = id;
  setBright(inst, prev, false); setBright(inst, id, true);
  // mobile mirrors the selection only through group rows
  const call = $(inst.el, '.call'), lead = $(inst.svg, '.lead'), dot = $(inst.svg, '.lead-dot');
  const apply = () => {
    call.innerHTML = calloutHTML(id);
    const P = inst.pos, pw = inst.podwayLeader;
    const bottomBox = { left: pw.boxLeft, top: pw.cardTop }, topBox = { left: 850, top: 92 }, topRight = { left: 1106, top: 92 };
    const h = call.offsetHeight, w = call.offsetWidth;
    const rects = $$(inst.el, '.glab').map((e) => ({ l: e.offsetLeft - 6, r: e.offsetLeft + e.offsetWidth + 6, t: e.offsetTop - 6, b: e.offsetTop + e.offsetHeight + 6 }));
    rects.push({ l: -1e4, r: 540, t: -1e4, b: 1e4 }, { l: -1e4, r: 1e4, t: -1e4, b: 84 });
    let place, pts;
    if (id === 'podway') { place = bottomBox; pts = [[pw.lx, pw.ly0], [pw.lx, pw.cardTop]]; }
    else {
      const opts = (id === 'gaori' ? [topBox] : id === 'dolgorae' ? [bottomBox] : [bottomBox, topBox, topRight]).map((b) => {
        const box = { l: b.left, r: b.left + w, t: b.top, b: b.top + h };
        const p = findLeader(id, box, rects);
        let len = Infinity; if (p) { len = 0; for (let i = 0; i < p.length - 1; i++) len += Math.hypot(p[i + 1][0] - p[i][0], p[i + 1][1] - p[i][1]); len += (p.length - 2) * 60; }
        return { b, p, len };
      }).sort((a, b) => a.len - b.len);
      place = opts[0].b; pts = opts[0].p;
    }
    call.style.left = `${place.left}px`; call.style.top = `${place.top}px`;
    if (pts) {
      lead.setAttribute('d', 'M ' + pts.map((q) => `${q[0].toFixed(1)} ${q[1].toFixed(1)}`).join(' L '));
      dot.setAttribute('cx', pts[0][0].toFixed(1)); dot.setAttribute('cy', pts[0][1].toFixed(1));
      lead.style.opacity = ''; dot.style.opacity = '';
      if (!STILL) { drawLine(lead, 380); play(dot, { opacity: 0, transform: 'scale(.4)' }, { opacity: '1', transform: 'scale(1)' }, 300); }
    } else { lead.style.opacity = '0'; dot.style.opacity = '0'; }
    play(call, { opacity: 0, transform: 'translateY(6px)' }, { opacity: '1', transform: 'translateY(0px)' }, 320);
  };
  clearTimeout(callTimer);
  if (STILL) { apply(); return; }
  // fade the old card and leader out, then re-anchor
  // fade from wherever each element is now (a second hover mid-fade must not flash it back)
  const cur = (e) => getComputedStyle(e).opacity;
  call.animate([{ opacity: cur(call) }, { opacity: 0 }], { duration: 200, easing: 'ease-in', fill: 'forwards' });
  lead.animate([{ opacity: cur(lead) }, { opacity: 0 }], { duration: 160, fill: 'forwards' });
  dot.animate([{ opacity: cur(dot) }, { opacity: 0 }], { duration: 160, fill: 'forwards' });
  callTimer = setTimeout(() => { for (const e of [call, lead, dot]) e.getAnimations().forEach((a) => a.cancel()); apply(); }, 210);
}
function tourStep(i) {
  if (!toured) return;
  select(TOUR[i % TOUR.length], { fromTour: true });
  at(clock + 5000, () => tourStep(i + 1));
}

// ---- interaction ----
(function wire() {
  let hoverT = 0;
  for (const el of $$(INST.d.svg, '.gear')) {
    // the machine is inspectable once it has assembled and its callout is up
    el.addEventListener('mouseenter', () => { if (!introDone) return; clearTimeout(hoverT); hoverT = setTimeout(() => select(el.dataset.id), 70); });
    el.addEventListener('mouseleave', () => clearTimeout(hoverT));
    el.addEventListener('click', () => { if (!introDone) return; clearTimeout(hoverT); select(el.dataset.id); });
  }
  // mobile: one open group at a time; its gears glow in the mechanism above
  let mobileTouched = false;
  const groupsEl = document.getElementById('groups');
  function glowGroup(gid, on) {
    const gr = GROUPS.find((x) => x.id === gid);
    for (const id of gr.ids) {
      setBright(INST.m, id, on);
      if (on) pulse($(gearEl(INST.m, id), '.fl'), 'opacity', 0.95, 1200);
    }
  }
  for (const row of $$(groupsEl, '.grp')) {
    row.addEventListener('click', () => {
      const gid = row.dataset.g, cur = INST.m.open;
      if (!mobileTouched) { mobileTouched = true; setBright(INST.m, SEL, false); }
      if (cur) {
        const r = $(groupsEl, `.grp[data-g="${cur}"]`), det = $(r, '.det');
        $(r, 'i').textContent = '›';
        if (det) {
          if (STILL) det.remove();
          else { const h = det.offsetHeight; det.animate([{ height: `${h}px`, opacity: 1, marginTop: '6px' }, { height: '0px', opacity: 0, marginTop: '0px', paddingTop: '0px', paddingBottom: '0px' }], { duration: 300, easing: EASE }).onfinish = () => det.remove(); }
        }
        glowGroup(cur, false);
      }
      INST.m.open = cur === gid ? null : gid;
      if (INST.m.open) {
        const gr = GROUPS.find((x) => x.id === gid);
        const det = document.createElement('div');
        det.className = 'det fx-panel';
        det.innerHTML = gr.ids.map((id) => `<p><b>${label(id)}</b>${G[id].role}</p>`).join('');
        row.appendChild(det); $(row, 'i').textContent = '⌄';
        if (!STILL) { const h = det.offsetHeight; det.animate([{ height: '0px', opacity: 0, marginTop: '0px', paddingTop: '0px', paddingBottom: '0px' }, { height: `${h}px`, opacity: 1, marginTop: '6px' }], { duration: 350, easing: EASE }); }
        glowGroup(gid, true);
      }
    });
  }
})();

// ---- the intro ----
function prime() { // everything the intro reveals starts hidden
  const inst = MOBILE ? INST.m : INST.d;
  for (const el of $$(document, '.msg > *')) el.style.opacity = '0';
  for (const el of $$(inst.svg, '.gear .arr')) el.style.opacity = '0';
  if (!MOBILE) {
    for (const el of [...$$(inst.el, '.glab'), $(inst.el, '.call'), $(inst.svg, '.arw-h'), $(inst.svg, '.lead-dot')]) el.style.opacity = '0';
    for (const el of [$(inst.svg, '.arw-a'), $(inst.svg, '.lead')]) { el.style.strokeDasharray = '1'; el.style.strokeDashoffset = '1'; }
  } else {
    for (const el of $$(document, '.grp, .mhint')) el.style.opacity = '0';
  }
}
function schedule() {
  const inst = MOBILE ? INST.m : INST.d;
  // 0 ms: the message column
  at(0, () => $$(document, '.msg > *').filter((e) => getComputedStyle(e).display !== 'none').forEach((el, i) =>
    play(el, { opacity: 0, transform: 'translateY(10px)' }, { opacity: '1', transform: 'translateY(0px)' }, 600, { delay: i * 90 })));
  const hop = bfs('aquarium'), tree = order.filter((id) => id !== 'aquarium').sort((a, b) => hop[a] - hop[b] || order.indexOf(a) - order.indexOf(b));
  if (!MOBILE) {
    // 400 ms: Aquarium draws itself; hub and < _ > follow
    at(400, () => {
      const el = gearEl(inst, 'aquarium'), arr = $(el, '.arr'); arr.style.opacity = '1';
      const tt = $(el, '.tt');
      drawLine(tt, 760);
      play(tt, { fillOpacity: 0 }, { fillOpacity: '.93' }, 520, { delay: 380 });
      for (const [sel, d] of [['.rim', 380], ['.win', 480], ['.hub', 560], ['.lab', 680]]) for (const c of $$(el, sel)) play(c, { opacity: 0 }, { opacity: '1' }, 420, { delay: d });
      setTimeout(() => { tt.style.strokeDasharray = ''; tt.style.strokeDashoffset = ''; }, 1250);
    });
    // 1000 ms on: the others arrive along their axes, tree order, 110 ms apart; a spark where the teeth engage
    tree.forEach((id, i) => at(1000 + i * 110, () => {
      const g = G[id], P = inst.pos[id], PP = inst.pos[g.parent], el = gearEl(inst, id), arr = $(el, '.arr');
      const L = Math.hypot(P.cx - PP.cx, P.cy - PP.cy), ux = (P.cx - PP.cx) / L, uy = (P.cy - PP.cy) / L;
      for (const t of $$(el, '.lab')) t.style.opacity = '0';
      play(arr, { opacity: 0, transform: `translate(${(ux * 16).toFixed(1)}px,${(uy * 16).toFixed(1)}px) scale(.92)` }, { opacity: '1', transform: 'translate(0px,0px) scale(1)' }, 520);
      at(clock + 470, () => {
        spark(inst, [PP.cx + ux * PP.r, PP.cy + uy * PP.r]);
        for (const t of $$(el, '.lab')) play(t, { opacity: 0 }, { opacity: '1' }, 320);
      });
    }));
    // 3100 ms: the drive gear's cue draws and the whole train spins up together
    at(3100, () => { drawLine($(inst.svg, '.arw-a'), 520); play($(inst.svg, '.arw-h'), { opacity: 0 }, { opacity: '1' }, 260, { delay: 420 }); spinAt = 3100; });
    at(3200, () => wave(inst));
    // 4400 ms: group labels, then Podway's callout and leader
    at(4400, () => $$(inst.el, '.glab').forEach((el, i) => play(el, { opacity: 0, transform: 'translateY(4px)' }, { opacity: '1', transform: 'translateY(0px)' }, 460, { delay: i * 80 })));
    at(4460, () => {
      const dot = $(inst.svg, '.lead-dot');
      play(dot, { opacity: 0, transform: 'scale(.4)' }, { opacity: '1', transform: 'scale(1)' }, 300);
      drawLine($(inst.svg, '.lead'), 420, 120);
      play($(inst.el, '.call'), { opacity: 0, transform: 'translateY(8px)' }, { opacity: '1', transform: 'translateY(0px)' }, 520, { delay: 380 });
      introDone = true;
    });
    at(9460, () => tourStep(1));
  } else {
    // mobile: rows follow the message; gears pop in outward, then spin up with the same wave
    at(300, () => [...$$(document, '.grp'), $(document, '.mhint')].forEach((el, i) =>
      play(el, { opacity: 0, transform: 'translateY(8px)' }, { opacity: '1', transform: 'translateY(0px)' }, 500, { delay: 200 + i * 70 })));
    at(400, () => play($(gearEl(inst, 'aquarium'), '.arr'), { opacity: 0, transform: 'scale(.9)' }, { opacity: '1', transform: 'scale(1)' }, 450));
    tree.forEach((id, i) => at(600 + i * 80, () => play($(gearEl(inst, id), '.arr'), { opacity: 0, transform: 'scale(.9)' }, { opacity: '1', transform: 'scale(1)' }, 450)));
    at(2100, () => { spinAt = 2100; });
    at(2200, () => wave(inst));
  }
  // idle: work packets, one route every 4.5 s
  const first = MOBILE ? 4200 : 5200;
  const nextPacket = (k) => { launchPacket(inst, k); at(clock + 4500, () => nextPacket(k + 1)); };
  at(first, () => nextPacket(0));
}
function spark(inst, [x, y]) {
  const layer = $(inst.svg, '.sparks');
  const c = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
  c.setAttribute('cx', x.toFixed(1)); c.setAttribute('cy', y.toFixed(1)); c.setAttribute('r', (8 * inst.scale).toFixed(1));
  c.setAttribute('fill', `url(#sp${inst.uid})`);
  c.style.transformBox = 'fill-box'; c.style.transformOrigin = 'center';
  layer.appendChild(c);
  c.animate([{ opacity: 0, transform: 'scale(.3)' }, { opacity: 1, transform: 'scale(1.15)', offset: 0.35 }, { opacity: 0, transform: 'scale(1.5)' }], { duration: 440, easing: 'ease-out' }).onfinish = () => c.remove();
}
function wave(inst) { // one gear drives all: a glow travels outward from Podway through the mesh
  const hop = bfs('podway');
  for (const id of order) setTimeout(() => pulse($(gearEl(inst, id), '.fl'), 'opacity', 0.9, 650), hop[id] * 90);
}

// ---- the frame loop: one clock for rotation, packets and the schedule ----
let last = null;
function frame(ts) {
  const dt = last == null ? 0 : Math.min(ts - last, 50); last = ts;
  if (running) {
    clock += dt;
    while (queue.length && queue[0].t <= clock) queue.shift().fn();
    const w = W_CRUISE * smooth((clock - spinAt) / SPIN_RAMP);
    theta += w * dt;
    applyRotation();
    updatePacket();
  }
  requestAnimationFrame(frame);
}

if (!STILL) {
  prime();
  schedule();
  const target = MOBILE ? INST.m.el : INST.d.el;
  const start = () => { if (running) return; document.fonts.ready.then(() => { running = true; }); };
  const io = new IntersectionObserver((es) => { if (es.some((e) => e.isIntersecting)) { io.disconnect(); start(); } }, { threshold: 0.35 });
  io.observe(target);
  requestAnimationFrame(frame);
}


  return () => {
    t_.forEach((id) => W_.clearTimeout(id)); i_.forEach((id) => W_.clearInterval(id)); r_.forEach((id) => W_.cancelAnimationFrame(id));
    o_.forEach((o) => o.disconnect()); off_.forEach((f) => f());
    // running animations are left alone: the site detaches the scene next, and cancelling them would reject
    // the `finished` promises the scene still awaits (AbortError)
  };
}
