// js/strengths/stack.js — 01 제품 · Every layer, down to the kernel.
// Generated by lab/formats/port-scenes.mjs from the approved prototype lab/formats/live/stack/index.html.
// Change the prototype and regenerate (node lab/formats/port-scenes.mjs); do not edit this file by hand.
export const css = `:host {
  --ink: #EDE9E7; --ink2: rgba(237,233,231,.78); --ink3: rgba(237,233,231,.6); --ink4: rgba(237,233,231,.32);
  --teal: #10C4BE; --teal2: #63DDD7; --cyan: #BFF3F0; --warm: #F4D7B8; --amber: #FFC285; --red: #FF6B76;
  --bg: #01080a; --panel: #041114; --panel2: #071a1f; --panel3: #0c2329;
  --line: rgba(237,233,231,.12); --line2: rgba(237,233,231,.2); --line3: rgba(237,233,231,.32);
  --teal-a1: rgba(16,196,190,.10); --teal-a2: rgba(16,196,190,.22); --teal-a3: rgba(16,196,190,.42);
  --amber-a1: rgba(255,194,133,.09); --amber-a2: rgba(255,194,133,.34);
  --font: "Pretendard Variable", Pretendard, -apple-system, BlinkMacSystemFont, "Apple SD Gothic Neo", "Noto Sans KR", sans-serif;
  --mono: "IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, "Pretendard Variable", Pretendard, monospace;
}
*, *::before, *::after { box-sizing: border-box; }
:host {    color: var(--ink); font-family: var(--font); -webkit-font-smoothing: antialiased; letter-spacing: -.005em; }
.mono { font-family: var(--mono); letter-spacing: 0; }
.msg { position: absolute; z-index: 10; left: 72px; top: 196px; width: 440px; }
.kick { display: flex; align-items: baseline; gap: 7px; font: 400 13px var(--mono); color: var(--ink); }
.kick .area { font-family: var(--font); font-size: 13.5px; color: var(--teal); }
.hook { margin: 20px 0 0; font-size: 50px; line-height: 1.06; font-weight: 600; letter-spacing: -.03em; }
.lede { margin: 26px 0 0; font-size: 17.5px; line-height: 1.72; font-weight: 500; word-break: keep-all; }
.more { display: inline-flex; gap: 8px; margin-top: 30px; padding-bottom: 4px; font-size: 14px; color: var(--ink2); border-bottom: 1px solid var(--line3); }
.hint { font-size: 12.5px; color: var(--ink3); }
.fx-tag { display: inline-flex; align-items: center; height: 18px; padding: 0 5px; border: 1px solid var(--line2); border-radius: 4px; font: 500 11px/1 var(--mono); letter-spacing: .03em; color: var(--ink3); white-space: nowrap; }
.fx-tag.tool { color: var(--teal2); border-color: var(--teal-a3); }
.fx-tag.ai { color: var(--cyan); border-color: rgba(191,243,240,.35); }
.fx-tag.human { color: var(--warm); border-color: rgba(244,215,184,.45); }
.fx-demo { display: inline-flex; align-items: center; height: 22px; padding: 0 7px; border-radius: 5px; border: 1px solid var(--amber-a2); font: 500 11px var(--mono); color: var(--amber); letter-spacing: .02em; }
.fx-panel { background: var(--panel); border: 1px solid var(--line); border-radius: 14px; }
.m-only { display: none; }
:host(.m) .msg { position: relative; left: auto; top: auto; width: auto; padding: 84px 20px 0; }
:host(.m) .kick { font-size: 12px; }
:host(.m) .kick .area { font-size: 12.5px; }
:host(.m) .hook { margin-top: 12px; font-size: 31px; line-height: 1.12; }
:host(.m) .lede { margin-top: 14px; font-size: 14.5px; line-height: 1.62; }
:host(.m) .more { display: none; }
:host(.m) .d-only { display: none !important; }
:host(.m) .m-only { display: block; }
:host(.pre) .msg, :host(.pre) #stage, :host(.pre) #mlist, :host(.pre) .mhint { visibility: hidden; }
:host(.still) *, :host(.still) *::before, :host(.still) *::after { transition: none !important; }
.stage { position: absolute; left: 0; top: 0; width: 1440px; height: 900px; z-index: 5; }
.stage svg { position: absolute; inset: 0; overflow: visible; }
.lab { position: absolute; transform: translate(-100%, -50%); text-align: right; white-space: nowrap; cursor: pointer; }
.lab .n { font-size: 16.5px; font-weight: 600; letter-spacing: -.01em; transition: color .45s ease; }
.lab .s { margin-left: 8px; font-size: 12px; color: var(--ink3); }
.lab .e { margin-top: 5px; font-size: 13px; color: var(--ink2); transition: color .45s ease; }
.lab.on .n { color: var(--teal2); }
.lab.on .e { color: var(--ink); }
.lab.root .n { color: var(--teal); }
.beam-lab { position: absolute; }
.beam-lab .k { font: 500 12px var(--mono); color: var(--teal2); letter-spacing: .02em; }
.beam-lab .t { margin-top: 4px; font-size: 13px; color: var(--ink2); }
.card { position: absolute; width: 250px; padding: 16px 18px 6px; overflow: hidden; transition: top .45s cubic-bezier(.2,.7,.2,1); }
.card h3 { margin: 0 0 12px; font-size: 15px; font-weight: 600; display: flex; align-items: baseline; gap: 8px; }
.card h3 .s { font-size: 12px; color: var(--ink3); font-weight: 400; }
.card dl { margin: 0; }
.card dt { font: 500 11px var(--mono); color: var(--teal2); letter-spacing: .03em; }
.card dt.ai { color: var(--cyan); }
.card dd { margin: 4px 0 12px; font-size: 13.5px; line-height: 1.55; color: var(--ink); word-break: keep-all; }
.foot { position: absolute; transform: translateX(-50%); white-space: nowrap; }
#stage .face { transition: stroke .45s ease, fill-opacity .45s ease, stroke-width .45s ease; }
#stage .rip, #stage .kring, #stage .pod, #stage .node, #stage .tap, #stage .cap { transform-box: fill-box; transform-origin: center; }
#stage .cyl { transform-box: fill-box; transform-origin: 50% 100%; }
#stage .ttag { font: 500 11px "IBM Plex Mono", monospace; fill: #8FF0EA; letter-spacing: .04em; }
.mlist { position: relative; z-index: 10; margin: 20px 20px 0; }
.mline { position: absolute; left: 19px; top: 22px; bottom: 22px; width: 1.5px; z-index: 0; transform-origin: 50% 0;
    background: linear-gradient(180deg, rgba(191,243,240,.9), rgba(16,196,190,.85)); box-shadow: 0 0 8px rgba(16,196,190,.7); }
.mpk { position: absolute; left: 11.75px; top: 0; width: 16px; height: 16px; z-index: 2; pointer-events: none; opacity: 0; border-radius: 50%;
    background: radial-gradient(circle, #F2FFFE 0 2.3px, rgba(191,243,240,.62) 3.4px, rgba(16,196,190,.18) 5.5px, rgba(16,196,190,0) 8px); }
.mpk.t { background: radial-gradient(circle, #E8FFFD 0 2.3px, rgba(99,221,215,.75) 3.4px, rgba(16,196,190,.25) 5.5px, rgba(16,196,190,0) 8px); }
.row { position: relative; z-index: 1; display: grid; grid-template-columns: 38px 1fr 12px; column-gap: 12px; row-gap: 0; align-items: center; padding: 7px 0; border-top: 1px solid var(--line); cursor: pointer; -webkit-tap-highlight-color: transparent; }
.row:last-child { border-bottom: 1px solid var(--line); }
.row .ico { width: 38px; height: 26px; overflow: visible; position: relative; z-index: 3; }
.row b { display: block; font-size: 14.5px; font-weight: 600; transition: color .35s ease; }
.row b .s { margin-left: 6px; font-size: 11.5px; font-weight: 400; color: var(--ink3); }
.row .e { display: block; margin-top: 1px; font-size: 12px; color: var(--ink2); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.row i { font-style: normal; color: var(--ink3); font-size: 16px; }
.row.on b { color: var(--teal2); }
.row.root b { color: var(--teal); }
.detw { grid-column: 2 / 4; margin-top: 12px; overflow: hidden; }
.det { margin: 1px 0 3px; padding: 10px 12px 1px; border-radius: 10px; }
.det dl { margin: 0; }
.det dt { font: 500 10px var(--mono); color: var(--teal2); letter-spacing: .03em; }
.det dt.ai { color: var(--cyan); }
.det dd { margin: 2px 0 8px; font-size: 12.5px; line-height: 1.48; word-break: keep-all; }
.mhint { margin: 10px 20px 0; position: relative; z-index: 10; }
:host(.m) .beam-lab, :host(.m) .lab, :host(.m) .card, :host(.m) .foot, :host(.m) #leader, :host(.m) #ldot { display: none; }
`;
export const html = `<div class="frame">
<section class="msg">
  <div class="kick"><span>01</span><span class="area">· 제품</span></div>
  <h2 class="hook">Every layer,<br>down to the kernel.</h2>
  <p class="lede">화면부터 Kernel까지, 제품의 모든 층을 다뤄 본 경험으로 AI&nbsp;Agent와 함께 만듭니다.</p>
  <a class="more" href="#svcDetails"></a>
</section>

<div class="visw"><div class="vis"><div class="stage" id="stage"></div></div></div>

<div class="m-only mlist" id="mlist"></div>
<p class="m-only hint mhint">층을 누르면 자세히 볼 수 있습니다</p>
</div>`;
export const crop = {"t":[520,76,1384,824],"m":[770,84,1102,764]};
export function run(env) {
  const { sr, host, still: STILL_, narrow: NARROW_, scale: SCALE_ = () => 1 } = env;
  const W_ = globalThis, D_ = W_.document;
  const t_ = new Set(), i_ = new Set(), r_ = new Set(), o_ = [], off_ = [];
  const setTimeout = (f, ms, ...a) => { const id = W_.setTimeout(() => { t_.delete(id); f(...a); }, ms); t_.add(id); return id; };
  const clearTimeout = (id) => { W_.clearTimeout(id); t_.delete(id); };
  const setInterval = (f, ms, ...a) => { const id = W_.setInterval(f, ms, ...a); i_.add(id); return id; };
  const clearInterval = (id) => { W_.clearInterval(id); i_.delete(id); };
  const requestAnimationFrame = (f) => { const id = W_.requestAnimationFrame((ts) => { r_.delete(id); f(ts); }); r_.add(id); return id; };
  const cancelAnimationFrame = (id) => { W_.cancelAnimationFrame(id); r_.delete(id); };
  const addEventListener = (t, f, o) => { W_.addEventListener(t, f, o); off_.push(() => W_.removeEventListener(t, f, o)); };
  const matchMedia = (q) => (/max-width:\s*760px/.test(q) ? { matches: NARROW_ } : /prefers-reduced-motion/.test(q) ? { matches: STILL_ } : W_.matchMedia(q));
  const location = { search: STILL_ ? '?still' : '' };
  // a visual shown as a crop (.visw clips it) is "in view" by what the crop shows, not by its whole design space
  const IntersectionObserver = class extends W_.IntersectionObserver { constructor(cb, o) { super(cb, o); o_.push(this); } observe(t) { return super.observe(t?.closest?.('.visw') || t); } };
  const ResizeObserver = class extends W_.ResizeObserver { constructor(cb) { super(cb); o_.push(this); } };
  const document = {
    getElementById: (id) => sr.getElementById(id),
    querySelector: (s) => sr.querySelector(s),
    querySelectorAll: (s) => sr.querySelectorAll(s),
    documentElement: host, body: host,
    createElement: (t, o) => D_.createElement(t, o), createElementNS: (n, t) => D_.createElementNS(n, t),
    createTextNode: (t) => D_.createTextNode(t), createDocumentFragment: () => D_.createDocumentFragment(),
    createTreeWalker: (...a) => D_.createTreeWalker(...a),
    get fonts() { return D_.fonts; }, get hidden() { return D_.hidden; }, get timeline() { return D_.timeline; },
  };


// Facts only (docs/reference/company.md, product.md, content.js). No counts, no patents on this screen.
const LAYERS = [
  { id: 'app', name: 'Web · App', sub: '화면', ev: 'Sudal 모바일 앱 · Doksuri 데스크톱 앱',
    exp: null,
    prod: ['Sudal · Flutter 모바일 앱과 웹 운영 도구', 'Doksuri · React·Tauri 데스크톱 앱'] },
  { id: 'server', name: 'Server', sub: 'API · 상태', ev: '실시간 세션 runtime · SQL 오케스트레이션',
    exp: ['SAP HANA · SQL 실행 오케스트레이션', '장애 시 세션 복구 설계'],
    prod: ['Sudal · gRPC 계약과 FSM으로 만든 세션 runtime'] },
  { id: 'security', name: 'Security', sub: '인증 · 권한', ev: '서버 권한 경계 · DB 보안 통신',
    exp: ['SAP HANA · 클라우드–온프레미스 DB 보안 통신 Tech&nbsp;Lead'],
    prod: ['Sudal · 권한 경계를 화면이 아닌 서버가 지킵니다', 'Doksuri · Agent마다 신원과 권한을 따로 둡니다'] },
  { id: 'data', name: 'Data', sub: 'DB · 트랜잭션', ev: 'SAP HANA RDBMS 코어 · PostgreSQL',
    exp: ['SAP HANA RDBMS 코어', '멀티테넌트 DB · 테넌트 생명주기 관리'],
    prod: ['Sudal · PostgreSQL 기준 데이터, Valkey 재연결 캐시, 낙관적 잠금'] },
  { id: 'infra', name: 'Infra', sub: 'Cloud · Kubernetes', ev: '클라우드 DB 인프라 · 탄력 자원 관리',
    exp: ['SAP HANA · 클라우드 DB 인프라 Tech&nbsp;Lead', 'CKA · CKAD'],
    prod: ['Doksuri · Docker 기반 서버'] },
  { id: 'kernel', name: 'Kernel', sub: 'OS', ev: 'Linux Kernel 프로세스 스케줄러',
    exp: ['LG전자 · 모바일 SoC용 Linux Kernel 프로세스 스케줄러', 'webOS 전력 관리'],
    prod: null },
];
const AI_LINE = 'AI&nbsp;Agent가 만들고, Gaori Test와 Mulgae Review로 검증합니다. 중요한 결정은 사람이 합니다.';
const SEL = 'data';
const N = LAYERS.length;

const detail = (L) => `
  <dl>
    ${L.exp ? `<dt>Experience</dt><dd>${L.exp.join('<br>')}</dd>` : ''}
    <dt class="ai">AI Agent · Tool</dt><dd>${AI_LINE}</dd>
    ${L.prod ? `<dt>Products</dt><dd>${L.prod.join('<br>')}</dd>` : ''}
  </dl>`;
const cardInner = (L) => `<h3>${L.name}<span class="s">${L.sub}</span></h3>${detail(L)}`;

const LOGO_L = '<path d="M39.5,0 L0,24 L0,33 L39.5,57 L39.5,44 L14,28.5 L39.5,13 Z" fill="#10C4BE"/>';
const LOGO_U = '<rect x="66" y="50" width="52" height="9" fill="#10C4BE"/>';
const LOGO_R = '<path d="M144,0 L182.5,24 L182.5,33 L144,57 L144,44 L169.5,28.5 L144,13 Z" fill="#EDE9E7"/>';

// ---------- helpers (MOTION.md: one family of easing, light and reveal) ----------
const STILL = document.documentElement.classList.contains('still');
const MOBILE = matchMedia('(max-width: 760px)').matches;
const EASE = 'cubic-bezier(.2,.7,.2,1)';
const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];
// A one-shot entrance: its first frame holds through the delay; its last keyframe is then written to inline style.
function play(el, kf, o) {
  const a = el.animate(kf, { fill: 'both', easing: EASE, ...o });
  const end = kf[kf.length - 1];
  a.finished.then(() => {
    for (const [k, v] of Object.entries(end)) if (k !== 'offset' && k !== 'easing' && k !== 'composite') el.style[k] = v;
    a.cancel();
  }, () => {});
  return a;
}
const clamp01 = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);
const lerp = (a, b, t) => a + (b - a) * t;
const eOut = (t) => 1 - Math.pow(1 - t, 3);
const eInOut = (t) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2);
const eBack = (t) => { const s = 1.15; return 1 + (s + 1) * Math.pow(t - 1, 3) + s * Math.pow(t - 1, 2); };
let sel = LAYERS.findIndex((l) => l.id === SEL);

// one clock for everything that moves geometry; effects are (start, duration, fn(p)) on that clock
let T0 = 0;
const now = () => performance.now() - T0;
const fx = [];
const at = (t, dur, fn) => fx.push({ t, dur, fn });
const later = (t, fn) => fx.push({ t, dur: 0, fn: () => fn() });

// ================= desktop: a live isometric stack =================
const CX = 936, W = 152, H = W / 2, T = 7, S = 90, CY0 = 214;
const cyOf = (i) => CY0 + i * S;
const MID = (cyOf(0) + cyOf(N - 1)) / 2, SLAB = 13;       // the product before it opens: one slab
const slabY = (i) => MID + (i - (N - 1) / 2) * SLAB;
const BEAM_TOP = 98, KU = 12;                               // the lantern; the beam lands on the kernel's underscore
const CARD_X = 1118, LIFT = 6;
const clampTop = (i, h) => Math.max(96, Math.min(cyOf(i) - 64, 900 - h - 24));
const TL = { slab: 300, lantern: 450, explode: 950, explodeDur: 1350, beamLab: 1900, agent0: 2150, agentGap: 150, flight: 650,
  scan: 650, test: 4300, testDur: 900, root: 5200, card: 5600, idle: 6000 };

const st = {
  cy: LAYERS.map((_, i) => (STILL ? cyOf(i) : slabY(i))),
  lift: LAYERS.map(() => 0), liftTo: LAYERS.map(() => 0),
  alpha: 0, sway: 0,                                         // sway amplitude ramps in when the stack is built
  agents: LAYERS.map(() => ({ mode: 'hidden', t: 0 })),
  pk: [], plane: null,
  scan: LAYERS.map(() => ({ x: -100, op: 0 })),
};

function P(i, u, v) {
  const c = Math.cos(st.alpha), s = Math.sin(st.alpha), cy = st.cy[i] - st.lift[i];
  const up = u * c - v * s, vp = u * s + v * c;
  return [CX + (up - vp) * W / 200, cy + (up + vp) * H / 200];
}
function isoM(i) {
  const c = Math.cos(st.alpha), s = Math.sin(st.alpha), cy = st.cy[i] - st.lift[i];
  return `matrix(${((c - s) * W / 200).toFixed(4)},${((c + s) * H / 200).toFixed(4)},${(-(s + c) * W / 200).toFixed(4)},${((c - s) * H / 200).toFixed(4)},${CX},${cy.toFixed(2)})`;
}
const pcy = (i) => st.cy[i] - st.lift[i];

const CYL_AT = [[-44, -34], [24, -34], [-10, 30]];
const KSC = 0.62, KW = 182.5 * KSC, KH = 57 * KSC;

(function buildDesktop() {
  const ns = 'vector-effect="non-scaling-stroke"';
  const pat = {
    app: `<rect ${ns} x="-80" y="-66" width="76" height="92" rx="4"/><line ${ns} x1="-80" y1="-50" x2="-4" y2="-50"/>
      <line class="cl" ${ns} x1="-68" y1="-34" x2="-24" y2="-34" stroke-opacity=".45"/><line class="cl" ${ns} x1="-68" y1="-20" x2="-36" y2="-20" stroke-opacity=".45"/>
      <rect class="cl" ${ns} x="-68" y="-6" width="52" height="20" rx="2" stroke-opacity=".45"/>
      <rect ${ns} x="18" y="-50" width="40" height="78" rx="8"/><line ${ns} x1="30" y1="-40" x2="46" y2="-40" stroke-opacity=".45"/>
      <rect class="screen" ${ns} x="26" y="-26" width="24" height="30" rx="2" stroke-opacity=".45" fill="#63DDD7" fill-opacity="0"/>
      <circle class="tap" ${ns} cx="38" cy="-11" r="13" stroke="#F2FFFE" stroke-width="1.4" opacity="0"/>`,
    server: `<line class="link" ${ns} x1="-58" y1="0" x2="58" y2="0" stroke-opacity=".5"/><line class="link" ${ns} x1="58" y1="0" x2="92" y2="0" stroke-dasharray="3 4" stroke-opacity=".6"/>
      <rect class="node" ${ns} x="-72" y="-14" width="28" height="28" rx="3" fill="#041114" fill-opacity=".7"/>
      <rect class="node" ${ns} x="-14" y="-14" width="28" height="28" rx="3" fill="#041114" fill-opacity=".7"/>
      <rect class="node" ${ns} x="44" y="-14" width="28" height="28" rx="3" fill="#041114" fill-opacity=".7"/>
      <line class="link" ${ns} x1="0" y1="14" x2="0" y2="56" stroke-opacity=".5"/><circle class="link" ${ns} cx="0" cy="62" r="6"/>`,
    security: `<rect class="perim" ${ns} x="-82" y="-82" width="164" height="164" rx="6" stroke-dasharray="5 5" stroke-opacity=".6"/>
      <rect class="inner" ${ns} x="-60" y="-60" width="120" height="120" rx="4" stroke-opacity=".35"/>
      <g class="lock"><path class="shackle" ${ns} d="M -14 -4 L -14 -16 A 14 14 0 0 1 14 -16 L 14 -4"/><rect class="lbody" ${ns} x="-20" y="-4" width="40" height="30" rx="3" fill="#041114" fill-opacity=".7"/></g>`,
    infra: (() => {
      let s = '';
      for (const u of [-54, -9, 36]) for (const v of [-54, -9, 36]) {
        const elastic = u === 36 && v === 36;
        s += `<rect class="pod${elastic ? ' elastic' : ''}" ${ns} x="${u}" y="${v}" width="26" height="26" rx="3" ${elastic ? 'stroke-dasharray="3 4" stroke-opacity=".5"' : ''}/>`;
      }
      return s;
    })(),
    data: '',
    // scheduler time slices along the kernel's front-right edge
    kernel: Array.from({ length: 9 }, (_, k) => `<line class="tick" ${ns} x1="78" y1="${-80 + k * 20}" x2="90" y2="${-80 + k * 20}" stroke-opacity=".28"/>`).join(''),
  };
  let svg = `<svg width="1440" height="900" viewBox="0 0 1440 900" aria-hidden="true">
    <defs>
      <filter id="glow" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="2.4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
      <filter id="glow2" x="-80%" y="-80%" width="260%" height="260%"><feGaussianBlur stdDeviation="7" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
      <linearGradient id="topf" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#10C4BE" stop-opacity=".16"/><stop offset="1" stop-color="#10C4BE" stop-opacity=".04"/></linearGradient>
      <linearGradient id="topOn" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#63DDD7" stop-opacity=".30"/><stop offset="1" stop-color="#10C4BE" stop-opacity=".08"/></linearGradient>
      <radialGradient id="halo"><stop offset="0" stop-color="#BFF3F0" stop-opacity=".75"/><stop offset=".35" stop-color="#63DDD7" stop-opacity=".25"/><stop offset="1" stop-color="#10C4BE" stop-opacity="0"/></radialGradient>
      <radialGradient id="haloA"><stop offset="0" stop-color="#E8FFFD" stop-opacity=".9"/><stop offset=".4" stop-color="#BFF3F0" stop-opacity=".3"/><stop offset="1" stop-color="#BFF3F0" stop-opacity="0"/></radialGradient>
      <linearGradient id="beam" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#BFF3F0" stop-opacity=".95"/><stop offset="1" stop-color="#10C4BE" stop-opacity=".85"/></linearGradient>
      <linearGradient id="bandG" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#BFF3F0" stop-opacity="0"/><stop offset="1" stop-color="#BFF3F0" stop-opacity=".38"/></linearGradient>
      <linearGradient id="atrailG" gradientUnits="userSpaceOnUse" x1="-34" y1="0" x2="-10" y2="0"><stop offset="0" stop-color="#BFF3F0" stop-opacity="0"/><stop offset="1" stop-color="#E8FFFD" stop-opacity=".8"/></linearGradient>
      <radialGradient id="haloW"><stop offset="0" stop-color="#FFE9D2" stop-opacity=".8"/><stop offset=".35" stop-color="#F4D7B8" stop-opacity=".28"/><stop offset="1" stop-color="#F4D7B8" stop-opacity="0"/></radialGradient>
      <linearGradient id="trailW" gradientUnits="userSpaceOnUse" x1="0" y1="-34" x2="0" y2="-2"><stop offset="0" stop-color="#F4D7B8" stop-opacity="0"/><stop offset="1" stop-color="#FFF3E6" stop-opacity=".85"/></linearGradient>
      <linearGradient id="trail" gradientUnits="userSpaceOnUse" x1="0" y1="-34" x2="0" y2="-2"><stop offset="0" stop-color="#BFF3F0" stop-opacity="0"/><stop offset="1" stop-color="#E8FFFD" stop-opacity=".85"/></linearGradient>
    </defs>
    <g id="rails" stroke="rgba(99,221,215,.22)" stroke-width="1" stroke-dasharray="2 5" opacity="${STILL ? 1 : 0}"><line/><line/><line/></g>
    <g id="plates">`;
  for (let i = N - 1; i >= 0; i--) {
    const L = LAYERS[i], on = i === sel, root = L.id === 'kernel';
    const edge = on ? '#63DDD7' : root ? '#10C4BE' : 'rgba(99,221,215,.62)';
    if (i < N - 1) svg += `<line class="beam" data-s="${i + 1}" stroke="url(#beam)" stroke-width="1.6" filter="url(#glow)" opacity=".9"/>`;
    let extra = '';
    if (L.id === 'data') extra = CYL_AT.map(() => {
      const rx = 15, ry = 6, h = 24;
      return `<g class="cylPos"><g class="cyl" stroke="#63DDD7" stroke-width="1.2" fill="#041114" fill-opacity=".85">
        <path d="M ${-rx} ${-h} L ${-rx} 0 A ${rx} ${ry} 0 0 0 ${rx} 0 L ${rx} ${-h}"/>
        <ellipse class="ctop" cx="0" cy="${-h}" rx="${rx}" ry="${ry}"/>
        <path d="M ${-rx} ${-h / 2} A ${rx} ${ry} 0 0 0 ${rx} ${-h / 2}" fill="none" stroke-opacity=".5"/></g></g>`;
    }).join('');
    if (root) extra = `<g class="kpos"><g class="klogo" filter="url(#glow2)"><g class="kl">${LOGO_L}</g><g class="ku">${LOGO_U}</g><g class="kr">${LOGO_R}</g><rect class="kflash" x="66" y="50" width="52" height="9" fill="#E8FFFD" opacity="0"/></g></g>`;
    svg += `<g class="plate" data-i="${i}">
      <polygon class="face lf" fill="#10C4BE" fill-opacity="${on || root ? .3 : .16}" stroke="${edge}" stroke-width="1"/>
      <polygon class="face rf" fill="#10C4BE" fill-opacity="${on || root ? .2 : .1}" stroke="${edge}" stroke-width="1"/>
      <polygon class="face top" fill="url(#${on || root ? 'topOn' : 'topf'})" stroke="${edge}" stroke-width="${on ? 1.6 : 1.1}" filter="url(#glow)"/>
      <g class="pat"><g class="iso" fill="none" stroke="#63DDD7" stroke-opacity=".75">${pat[L.id]}</g>${extra}</g>
      <g class="scanG"><rect class="band" x="-136" y="-100" width="36" height="200" fill="url(#bandG)" opacity="0"/><line class="scan" ${ns} x1="0" y1="-100" x2="0" y2="100" stroke="#E8FFFD" stroke-width="2" opacity="0"/></g>
      ${root ? '' : `<ellipse class="ring" rx="9" ry="4.5" fill="none" stroke="#BFF3F0" stroke-width="1.2" opacity="${STILL ? .95 : 0}" filter="url(#glow)"/><ellipse class="rip" rx="9" ry="4.5" fill="none" stroke="#BFF3F0" stroke-width="1.2" opacity="0"/>`}
    </g>`;
    if (root) svg += `<ellipse class="kring" rx="${W}" ry="${H}" fill="none" stroke="#63DDD7" stroke-width="1.2" opacity="0"/>`;
  }
  svg += `</g>
    <line class="beam" data-s="0" stroke="url(#beam)" stroke-width="1.6" filter="url(#glow)"/>
    <circle class="halo" cx="${CX}" cy="${BEAM_TOP}" r="22" fill="url(#halo)"/><circle class="core" cx="${CX}" cy="${BEAM_TOP}" r="4.5" fill="#F2FFFE"/>
    <g id="tplane" opacity="0"><polygon class="tp" fill="rgba(99,221,215,.05)" stroke="#8FF0EA" stroke-width="1.5" filter="url(#glow)"/><text class="ttag">Gaori · Test</text></g>
    <line id="leader" stroke="#63DDD7" stroke-width="1" opacity=".8"/><circle id="ldot" r="3" fill="#63DDD7" filter="url(#glow)"/>
    <g id="wbeams">${LAYERS.map(() => `<line class="wbeam" stroke="#BFF3F0" stroke-width="1.2" stroke-dasharray="2 3" opacity="0"/>`).join('')}</g>
    <g id="agents">${LAYERS.map(() => `<g class="agent" opacity="0"><line class="atrail" x1="-34" y1="0" x2="-10" y2="0" stroke="url(#atrailG)" stroke-width="2.6" stroke-linecap="round" opacity="0"/><circle r="17" fill="url(#haloA)"/><rect class="cap" x="-10" y="-3" width="20" height="6" rx="3" fill="#BFF3F0"/></g>`).join('')}</g>
    <g id="pkts">${[0, 1, 2, 3].map(() => `<g class="pkt" opacity="0"><g class="dir"><line class="ptr" x1="0" y1="-40" x2="0" y2="-2" stroke="url(#trail)" stroke-width="2.4" stroke-linecap="round"/></g><circle class="phl" r="16" fill="url(#halo)"/><circle class="pcore" r="3.4" fill="#F2FFFE"/></g>`).join('')}</g>
    <rect id="hit" x="${CX - W - 12}" y="${cyOf(0) - H}" width="${2 * W + 24}" height="${cyOf(N - 1) - cyOf(0) + 2 * H + T}" fill="transparent" pointer-events="all" style="cursor:pointer"/>
  </svg>`;
  let html = svg;
  LAYERS.forEach((L, i) => {
    const cls = ['lab', i === sel ? 'on' : '', L.id === 'kernel' ? 'root' : ''].join(' ');
    html += `<div class="${cls}" data-i="${i}" style="left:${CX - W - 28}px;top:${cyOf(i) + 4}px"><div><span class="n">${L.name}</span><span class="s">${L.sub}</span></div><div class="e">${L.ev}</div></div>`;
  });
  html += `<div class="beam-lab" style="right:${1440 - CX + 22}px;top:86px;text-align:right"><div class="k">AI Agent + Tool</div><div class="t">모든 층을 같은 방식으로 만들고 검증합니다</div></div>`;
  html += `<div class="card fx-panel" id="card" style="left:${CARD_X}px;top:${cyOf(sel) - 64}px"><div class="cin">${cardInner(LAYERS[sel])}</div></div>`;
  html += `<div class="foot hint" style="left:${CX}px;top:${cyOf(N - 1) + H + 44}px">층을 누르면 자세히 볼 수 있습니다</div>`;
  document.getElementById('stage').innerHTML = html;
})();

const stage = $('#stage');
const plates = [], labs = [];
$$('.plate', stage).forEach((g) => { plates[+g.dataset.i] = g; });
$$('.lab', stage).forEach((d) => { labs[+d.dataset.i] = d; });
const card = $('#card'), cin = $('.cin', card), leader = $('#leader'), ldot = $('#ldot');
const beams = []; $$('.beam', stage).forEach((l) => { beams[+l.dataset.s] = l; });
const rails = $$('#rails line', stage), agents = $$('.agent', stage), pkts = $$('.pkt', stage);
const tplane = $('#tplane', stage), tpPoly = $('.tp', tplane), tpTag = $('.ttag', tplane);
const parts = plates.map((g) => ({
  top: $('.top', g), lf: $('.lf', g), rf: $('.rf', g), iso: $('.iso', g), scanG: $('.scanG', g), scan: $('.scan', g),
  ring: $('.ring', g), rip: $('.rip', g), cyls: $$('.cylPos', g), kpos: $('.kpos', g), pat: $('.pat', g),
}));
const kring = $('.kring', stage);
const wbeams = $$('.wbeam', stage);
parts.forEach((p, i) => { p.band = $('.band', plates[i]); });

// ---- render the geometry of this instant ----
const f1 = (n) => n.toFixed(1);
function dock(i) {
  const [x, y] = P(i, 58, -100);
  return [x + 10, y - 11];
}
function render(t) {
  for (let i = 0; i < N; i++) {
    const p = parts[i], cy = pcy(i);
    const L = P(i, -100, 100), B = P(i, -100, -100), R = P(i, 100, -100), F = P(i, 100, 100);
    const pt = (q, dy = 0) => `${f1(q[0])},${f1(q[1] + dy)}`;
    p.top.setAttribute('points', `${pt(L)} ${pt(B)} ${pt(R)} ${pt(F)}`);
    p.lf.setAttribute('points', `${pt(L)} ${pt(F)} ${pt(F, T)} ${pt(L, T)}`);
    p.rf.setAttribute('points', `${pt(F)} ${pt(R)} ${pt(R, T)} ${pt(F, T)}`);
    const m = isoM(i);
    p.iso.setAttribute('transform', m); p.scanG.setAttribute('transform', m);
    p.cyls.forEach((c, k) => { const [x, y] = P(i, CYL_AT[k][0], CYL_AT[k][1]); c.setAttribute('transform', `translate(${f1(x)},${f1(y)})`); });
    if (p.kpos) p.kpos.setAttribute('transform', `translate(${f1(CX - KW / 2)},${f1(cy - KH - 4)}) scale(${KSC})`);
    if (p.ring) { for (const e of [p.ring, p.rip]) { e.setAttribute('cx', CX); e.setAttribute('cy', f1(cy)); } }
    p.corners = { L, B, R, F };
  }
  kring.setAttribute('cx', CX); kring.setAttribute('cy', f1(pcy(N - 1)));
  beams[0].setAttribute('x1', CX); beams[0].setAttribute('y1', BEAM_TOP); beams[0].setAttribute('x2', CX); beams[0].setAttribute('y2', f1(pcy(0)));
  for (let i = 1; i < N; i++) {
    const b = beams[i];
    b.setAttribute('x1', CX); b.setAttribute('y1', f1(pcy(i - 1)));
    b.setAttribute('x2', CX); b.setAttribute('y2', f1(pcy(i) - (i === N - 1 ? KU : 0)));
  }
  const c0 = parts[0].corners, c5 = parts[N - 1].corners;
  [['L', 0], ['R', 0], ['F', H]].forEach(([k], j) => {
    rails[j].setAttribute('x1', f1(c0[k][0])); rails[j].setAttribute('y1', f1(c0[k][1]));
    rails[j].setAttribute('x2', f1(c5[k][0])); rails[j].setAttribute('y2', f1(c5[k][1]));
  });
  labs.forEach((d, i) => { d.style.top = f1(st.cy[i] + 4) + 'px'; });
  // leader: from the selected plate's right corner to the card
  const R = parts[sel].corners.R;
  leader.setAttribute('x1', f1(R[0] + 6)); leader.setAttribute('y1', f1(R[1])); leader.setAttribute('x2', CARD_X); leader.setAttribute('y2', f1(R[1]));
  ldot.setAttribute('cx', f1(R[0])); ldot.setAttribute('cy', f1(R[1]));
  // scans: the line, its band, and the beam from the layer's agent to the line's near end
  st.scan.forEach((sc, i) => {
    const p = parts[i];
    p.scan.setAttribute('x1', f1(sc.x)); p.scan.setAttribute('x2', f1(sc.x)); p.scan.setAttribute('opacity', sc.op.toFixed(2));
    p.band.setAttribute('x', f1(sc.x - 36)); p.band.setAttribute('opacity', sc.op.toFixed(2));
    const a = st.agents[i], wb = wbeams[i];
    if (sc.op > 0.02 && a.mode === 'dock') {
      const [ax, ay] = dock(i), [ex, ey] = P(i, sc.x, -100);
      wb.setAttribute('x1', f1(ax)); wb.setAttribute('y1', f1(ay + 3)); wb.setAttribute('x2', f1(ex)); wb.setAttribute('y2', f1(ey));
      wb.setAttribute('opacity', (sc.op * .85).toFixed(2));
    } else wb.setAttribute('opacity', 0);
  });
  // agents: flying out of the lantern, then stationed on their layer
  st.agents.forEach((a, i) => {
    const el = agents[i];
    if (a.mode === 'hidden') { el.setAttribute('opacity', 0); return; }
    const [dx, dy] = dock(i);
    let x = dx, y = dy, rot = 0, op = 1;
    if (a.mode === 'fly') {
      const q = clamp01((t - a.t) / TL.flight), e = eInOut(q);
      const x0 = CX, y0 = BEAM_TOP, x1 = CX + 250, y1 = (BEAM_TOP + dy) / 2 - 30;
      const bx = (1 - e) * (1 - e) * x0 + 2 * (1 - e) * e * x1 + e * e * dx, by = (1 - e) * (1 - e) * y0 + 2 * (1 - e) * e * y1 + e * e * dy;
      const tx = 2 * (1 - e) * (x1 - x0) + 2 * e * (dx - x1), ty = 2 * (1 - e) * (y1 - y0) + 2 * e * (dy - y1);
      x = bx; y = by; rot = Math.atan2(ty, tx) * 180 / Math.PI * (1 - clamp01((q - 0.75) / 0.25)); op = clamp01(q * 5);
      el.firstElementChild.setAttribute('opacity', (Math.sin(Math.min(1, q * 1.15) * Math.PI) * .95).toFixed(2));
      if (q >= 1) { a.mode = 'dock'; el.firstElementChild.setAttribute('opacity', 0); }
    } else {
      y += Math.sin(t / 620 + i * 1.3) * 1.8;
    }
    el.setAttribute('opacity', op.toFixed(2));
    el.setAttribute('transform', `translate(${f1(x)},${f1(y)}) rotate(${rot.toFixed(1)})`);
  });
  // packets on the beam: requests go down, answers come back up
  for (const k of st.pk) {
    const q = clamp01((t - k.t) / k.dur), yTop = pcy(0), yBot = pcy(N - 1) - KU;
    const y = k.dir > 0 ? lerp(yTop, yBot, q) : lerp(yBot, yTop, q);
    const op = Math.min(1, q / 0.06, (1 - q) / 0.08);
    k.el.setAttribute('opacity', Math.max(0, op).toFixed(2));
    k.el.setAttribute('transform', `translate(${CX},${f1(y)})`);
    $('.dir', k.el).setAttribute('transform', k.dir > 0 ? '' : 'rotate(180)');
    // what the packet passes, happens
    for (let i = 1; i < N - 1; i++) { const yi = pcy(i); if (k.prev !== undefined && (k.prev - yi) * (y - yi) <= 0 && k.prev !== y) micro(i, k.dir); }
    k.prev = y;
    if (q >= 1 && !k.done) { k.done = true; k.onEnd && k.onEnd(); }
  }
  st.pk = st.pk.filter((k) => !(k.done && t - k.t > k.dur + 60) || (k.el.setAttribute('opacity', 0), false));
  // the Tool test plane
  if (st.plane) {
    const q = clamp01((t - st.plane.t) / st.plane.dur), yA = pcy(0) - 26, yB = pcy(N - 1);
    const y = lerp(yA, yB, eInOut(q)), k = 1.12, c = Math.cos(st.alpha), s = Math.sin(st.alpha);
    const Q = (u, v) => { const up = u * c - v * s, vp = u * s + v * c; return [CX + (up - vp) * W / 200 * k, y + (up + vp) * H / 200 * k]; };
    const pts = [Q(-100, 100), Q(-100, -100), Q(100, -100), Q(100, 100)];
    tpPoly.setAttribute('points', pts.map((p) => `${f1(p[0])},${f1(p[1])}`).join(' '));
    tpTag.setAttribute('x', f1(pts[2][0] + 14)); tpTag.setAttribute('y', f1(pts[2][1] + 4));
    tplane.setAttribute('opacity', Math.min(1, q / 0.08, (1 - q) / 0.1).toFixed(2));
    for (let i = 0; i < N; i++) { const yi = pcy(i); if (st.plane.prev !== undefined && (st.plane.prev - yi) * (y - yi) <= 0 && st.plane.prev !== y) tested(i); }
    st.plane.prev = y;
    if (q >= 1) { st.plane = null; tplane.setAttribute('opacity', 0); }
  }
}

// ---- small events on a layer ----
function ripple(i) {
  const r = parts[i].rip;
  if (r) r.animate([{ opacity: .95, transform: 'scale(1)' }, { opacity: 0, transform: 'scale(2.6)' }], { duration: 700, easing: 'cubic-bezier(.2,.6,.3,1)' });
}
function labFlash(i) {
  const e = $('.e', labs[i]), base = getComputedStyle(e).color;
  e.animate([{ color: base }, { color: '#FFFFFF', offset: .25 }, { color: base }], { duration: 900 });
}
function flashStroke(el, dur = 520, delay = 0) {
  el.animate([{ stroke: '#63DDD7', strokeOpacity: .75 }, { stroke: '#F2FFFE', strokeOpacity: 1, offset: .3 }, { stroke: '#63DDD7', strokeOpacity: .75 }], { duration: dur, delay });
}
let reqN = 0;
function micro(i, dir) {
  const g = plates[i], id = LAYERS[i].id;
  ripple(i); labFlash(i);
  if (id === 'server') $$('.node', g).forEach((n, k, all) => flashStroke(n, 520, (dir > 0 ? k : all.length - 1 - k) * 90));
  if (id === 'security') {
    $('.perim', g).animate([{ strokeDashoffset: 0 }, { strokeDashoffset: dir > 0 ? -20 : 20 }], { duration: 700, easing: 'ease-out' });
    const d = 5 * 100 / H;
    $('.shackle', g).animate([{ transform: 'translate(0px,0px)' }, { transform: `translate(${d}px,${d}px)`, offset: .35 }, { transform: 'translate(0px,0px)' }], { duration: 460, easing: EASE });
    flashStroke($('.lbody', g), 520);
  }
  if (id === 'data') $$('.ctop', g).forEach((c, k) => c.animate([{ fill: '#041114' }, { fill: '#63DDD7', offset: .3 }, { fill: '#041114' }], { duration: 560, delay: k * 70 }));
  if (id === 'infra') {
    $$('.pod:not(.elastic)', g).forEach((n, k) => flashStroke(n, 420, k * 35));
    if (dir > 0 && reqN % 2 === 0) $('.elastic', g).animate([
      { strokeDasharray: '3 4', strokeOpacity: .5 }, { strokeDasharray: '0', strokeOpacity: 1, stroke: '#F2FFFE', offset: .12 },
      { strokeDasharray: '0', strokeOpacity: 1, offset: .82 }, { strokeDasharray: '3 4', strokeOpacity: .5 }], { duration: 1700 });
  }
}
function kernelHit() {
  $('.kflash', stage).animate([{ opacity: 0 }, { opacity: .85, offset: .3 }, { opacity: 0 }], { duration: 700 });
  $$('.tick', plates[N - 1]).forEach((tk, k) => tk.animate([{ strokeOpacity: .28 }, { strokeOpacity: 1, stroke: '#F2FFFE', offset: .3 }, { strokeOpacity: .28 }], { duration: 420, delay: k * 50 }));
  labFlash(N - 1);
}
function appTap() {
  const g = plates[0];
  $('.tap', g).animate([{ opacity: .95, transform: 'scale(.25)' }, { opacity: 0, transform: 'scale(1.5)' }], { duration: 700, easing: 'cubic-bezier(.2,.6,.3,1)' });
  labFlash(0);
}
function appAnswer() {
  const g = plates[0];
  $('.screen', g).animate([{ fillOpacity: 0 }, { fillOpacity: .55, offset: .25 }, { fillOpacity: 0 }], { duration: 760 });
  $$('.cl', g).forEach((c, k) => flashStroke(c, 520, 80 + k * 70));
}
function tested(i) {
  const top = parts[i].top;
  top.animate([{ stroke: '#63DDD7' }, { stroke: '#F2FFFE', strokeWidth: 2.4, offset: .3 }, { stroke: getComputedStyle(top).stroke }], { duration: 620 });
  if (i < N - 1) ripple(i);
}
// an AI Agent sweeps its layer (build during the intro, a quiet rework later)
function scan(i, t, dur, strong) {
  at(t, dur, (q) => {
    st.scan[i].x = -100 + 200 * eInOut(q);
    st.scan[i].op = q >= 1 ? 0 : Math.min(1, Math.sin(q * Math.PI) * 1.6) * (strong ? 1 : .75);
  });
}
function launchPacket(dir, t, dur, onEnd) {
  const el = pkts.find((p) => !st.pk.some((k) => k.el === p));
  if (!el) return;
  // a request is cyan on its way down; its answer is warm on its way back up to the person using the app
  $('.ptr', el).setAttribute('stroke', dir > 0 ? 'url(#trail)' : 'url(#trailW)');
  $('.phl', el).setAttribute('fill', dir > 0 ? 'url(#halo)' : 'url(#haloW)');
  $('.pcore', el).setAttribute('fill', dir > 0 ? '#F2FFFE' : '#FFF6EC');
  st.pk.push({ el, dir, t, dur, onEnd });
}

// ---- selection (tour and hover) ----
function paintPlate(i, on) {
  const g = plates[i], root = LAYERS[i].id === 'kernel';
  const edge = on ? '#63DDD7' : root ? '#10C4BE' : 'rgba(99,221,215,.62)';
  for (const f of $$('.face', g)) f.style.stroke = edge;
  $('.lf', g).style.fillOpacity = on || root ? .3 : .16;
  $('.rf', g).style.fillOpacity = on || root ? .2 : .1;
  const top = $('.top', g);
  top.setAttribute('fill', `url(#${on || root ? 'topOn' : 'topf'})`);
  top.style.strokeWidth = on ? 1.6 : 1.1;
}
function moveCard() {
  const i = sel, L = LAYERS[i];
  if (STILL) { cin.innerHTML = cardInner(L); card.style.top = clampTop(i, card.offsetHeight) + 'px'; return; }
  card.getAnimations().forEach((a) => a.cancel());
  cin.getAnimations().forEach((a) => a.cancel());
  const h0 = card.offsetHeight;
  const out = cin.animate([{ opacity: 1 }, { opacity: 0 }], { duration: 150, fill: 'forwards' });
  out.finished.then(() => {
    cin.innerHTML = cardInner(L);
    const h1 = card.offsetHeight;
    card.style.top = clampTop(i, h1) + 'px';
    card.animate([{ height: h0 + 'px' }, { height: h1 + 'px' }], { duration: 320, easing: EASE });
    out.cancel();
    cin.animate([{ opacity: 0 }, { opacity: 1 }], { duration: 260 });
  }, () => {});
  leader.animate([{ opacity: 0 }, { opacity: .8 }], { duration: 380 });
}
function select(i) {
  if (i === sel) return;
  const prev = sel; sel = i;
  paintPlate(prev, false); paintPlate(i, true);
  st.liftTo[prev] = 0; st.liftTo[i] = STILL ? 0 : LIFT;
  labs[prev].classList.remove('on'); labs[i].classList.add('on');
  moveCard();
}
// HERO: the site (lab/formats/port-scenes.mjs) wraps the stage in .visw and shows it on phones too, above the list
const HERO = !!document.querySelector('.visw');
let tour = !STILL && !(MOBILE && HERO), interactive = STILL, hoverT = 0;
function onUser(i, nowSel) {
  if (!interactive) return;
  tour = false;
  clearTimeout(hoverT);
  if (nowSel) select(i); else hoverT = setTimeout(() => select(i), 70);
}
const layerAt = (e) => {
  const r = stage.getBoundingClientRect(), y = (e.clientY - r.top) * 900 / r.height;
  return Math.max(0, Math.min(N - 1, Math.round((y - CY0) / S)));
};
const hit = $('#hit', stage);
let lastHover = -1;
hit.addEventListener('mousemove', (e) => { const i = layerAt(e); if (i !== lastHover) { lastHover = i; onUser(i); } });
hit.addEventListener('mouseleave', () => { lastHover = -1; });
// on a phone the stack's card is the list below it: a tap on a plate opens that layer's row
hit.addEventListener('click', (e) => { if (MOBILE) { if (interactive) mrows[layerAt(e)]?.click(); return; } onUser(layerAt(e), true); });
labs.forEach((d, i) => { d.addEventListener('mouseenter', () => onUser(i)); d.addEventListener('click', () => onUser(i, true)); });

// ---- the intro, then a living system ----
function entrance(i) {
  const g = plates[i], L = LAYERS[i], fade = (el, d, dur = 360) => play(el, [{ opacity: 0 }, { opacity: 1 }], { duration: dur, delay: d });
  play(parts[i].pat, [{ opacity: i === 0 ? .5 : 0 }, { opacity: 1 }], { duration: 300 });
  if (L.id === 'app') $$('.iso > *:not(.tap)', g).forEach((el, k) => flashStroke(el, 520, k * 40));
  if (L.id === 'server') {
    $$('.node', g).forEach((el, k) => play(el, [{ opacity: 0, transform: 'scale(.4)' }, { opacity: 1, transform: 'scale(1)' }], { duration: 380, delay: 60 + k * 110 }));
    $$('.link', g).forEach((el) => fade(el, 360, 420));
  }
  if (L.id === 'security') {
    play($('.perim', g), [{ opacity: 0, strokeDashoffset: 30 }, { opacity: 1, strokeDashoffset: 0 }], { duration: 800, easing: 'cubic-bezier(.3,.6,.3,1)' });
    fade($('.inner', g), 180);
    const d = 12 * 100 / H;
    play($('.lock', g), [{ opacity: 0, transform: `translate(${-d}px, ${-d}px)` }, { opacity: 1, transform: 'translate(0px, 0px)' }], { duration: 480, delay: 300 });
  }
  if (L.id === 'data') $$('.cyl', g).forEach((el, k) => play(el, [{ opacity: 0, transform: 'scaleY(0)' }, { opacity: 1, transform: 'scaleY(1)' }], { duration: 520, delay: 80 + k * 110 }));
  if (L.id === 'infra') $$('.pod', g).forEach((el, k, all) => play(el, [{ opacity: 0, transform: 'scale(.5)' }, { opacity: 1, transform: 'scale(1)' }],
    { duration: 340, delay: 60 + k * 45 + (k === all.length - 1 ? 160 : 0) }));
  if (L.id === 'kernel') $$('.tick', g).forEach((el, k) => fade(el, 80 + k * 40, 300));
  $('.top', g).animate([{ stroke: '#63DDD7' }, { stroke: '#E8FFFD', strokeWidth: 2.2, offset: .35 }, { stroke: getComputedStyle($('.top', g)).stroke }], { duration: 650 });
}

function introDesktop() {
  // 1) the product as one slab, lit from above
  play($('#plates', stage), [{ opacity: 0, transform: 'translateY(10px)' }, { opacity: 1, transform: 'none' }], { duration: 600, delay: TL.slab });
  parts.forEach((p, i) => { p.pat.style.opacity = i === 0 ? .5 : 0; });
  $$('.kl, .ku, .kr', stage).forEach((e) => { e.style.opacity = 0; });
  play($('.halo', stage), [{ opacity: 0, transform: 'scale(0)' }, { opacity: 1, transform: 'scale(1)' }], { duration: 700, delay: TL.lantern });
  play($('.core', stage), [{ opacity: 0 }, { opacity: 1 }], { duration: 400, delay: TL.lantern });
  // 2) it opens into its layers
  at(TL.explode, TL.explodeDur, (q) => {
    for (let i = 0; i < N; i++) {
      const qi = clamp01((q * TL.explodeDur - i * 45) / (TL.explodeDur - (N - 1) * 45));
      st.cy[i] = lerp(slabY(i), cyOf(i), eBack(qi));
    }
  });
  play($('#rails', stage), [{ opacity: 0 }, { opacity: 1 }], { duration: 900, delay: TL.explode + 500, easing: 'linear' });
  $$('.ring', stage).forEach((r) => play(r, [{ opacity: 0 }, { opacity: .95 }], { duration: 500, delay: TL.explode + TL.explodeDur - 200 }));
  LAYERS.forEach((L, i) => {
    const [r1, r2] = labs[i].children, d = TL.explode + 520 + i * 70;
    play(r1, [{ opacity: 0, transform: 'translateX(-8px)' }, { opacity: 1, transform: 'none' }], { duration: 450, delay: d });
    play(r2, [{ opacity: 0, transform: 'translateX(-8px)' }, { opacity: 1, transform: 'none' }], { duration: 450, delay: d + 90 });
  });
  // 3) AI Agents leave the lantern, one per layer, and build it
  play($('.beam-lab', stage), [{ opacity: 0, transform: 'translateY(6px)' }, { opacity: 1, transform: 'none' }], { duration: 500, delay: TL.beamLab });
  LAYERS.forEach((L, i) => {
    const t = TL.agent0 + i * TL.agentGap;
    later(t, () => { st.agents[i] = { mode: 'fly', t }; });
    later(t + TL.flight, () => entrance(i));
    scan(i, t + TL.flight, TL.scan, true);
  });
  // 4) a Tool (Gaori) tests every layer, top to bottom — and the kernel lights up
  later(TL.test, () => { st.plane = { t: TL.test, dur: TL.testDur }; });
  const kx = 40 / KSC;
  play($('.kl', stage), [{ opacity: 0, transform: `translateX(${-kx}px)` }, { opacity: 1, transform: 'translateX(0px)' }], { duration: 650, delay: TL.root - 120 });
  play($('.kr', stage), [{ opacity: 0, transform: `translateX(${kx}px)` }, { opacity: 1, transform: 'translateX(0px)' }], { duration: 650, delay: TL.root - 120 });
  play($('.ku', stage), [{ opacity: 0 }, { opacity: 1 }], { duration: 260, delay: TL.root });
  $('.kflash', stage).animate([{ opacity: 0 }, { opacity: 1, offset: .3 }, { opacity: 0 }], { duration: 900, delay: TL.root });
  kring.animate([{ opacity: .75, transform: 'scale(.12)' }, { opacity: 0, transform: 'scale(1.35)' }], { duration: 1400, delay: TL.root + 60, easing: EASE });
  // 5) the explanation
  play(leader, [{ opacity: 0 }, { opacity: .8 }], { duration: 380, delay: TL.card + 60 });
  play(ldot, [{ opacity: 0 }, { opacity: 1 }], { duration: 300, delay: TL.card });
  play(card, [{ opacity: 0, transform: 'translateY(8px)' }, { opacity: 1, transform: 'none' }], { duration: 520, delay: TL.card + 120 });
  play($('.foot', stage), [{ opacity: 0 }, { opacity: 1 }], { duration: 600, delay: TL.card + 500 });
  later(TL.card, () => { st.liftTo[sel] = LIFT; interactive = true; });
  // 6) the product runs: requests pass every layer and the answers come back; the stack turns a little
  later(TL.idle, () => { st.swayT = now(); });
  const REQ = 2000, DOWN = 1300, UP = 1150;
  const request = (t) => {
    reqN++;
    appTap();
    launchPacket(1, t, DOWN, () => { kernelHit(); const t2 = now() + 140; later(t2, () => launchPacket(-1, t2, UP, appAnswer)); });
    later(t + REQ, () => request(t + REQ));
  };
  later(TL.idle + 300, () => request(TL.idle + 300));
  // the stationed agents keep working: one quiet rework sweep at a time
  let rw = 0;
  const rework = (t) => {
    const i = rw++ % N;
    scan(i, t, 800, false);
    agents[i].querySelector('.cap').animate([{ transform: 'scale(1)', fill: '#BFF3F0' }, { transform: 'scale(1.6)', fill: '#F2FFFE', offset: .3 }, { transform: 'scale(1)', fill: '#BFF3F0' }], { duration: 800 });
    later(t + 3100, () => rework(t + 3100));
  };
  later(TL.idle + 2200, () => rework(TL.idle + 2200));
  const tourStep = (t) => { if (!tour) return; select((sel + 1) % N); later(t + 4500, () => tourStep(t + 4500)); };
  later(TL.idle + 3500, () => tourStep(TL.idle + 3500));
}

function loop() {
  const t = now();
  for (let k = 0; k < fx.length; k++) {
    const e = fx[k];
    if (t < e.t) continue;
    const q = e.dur ? clamp01((t - e.t) / e.dur) : 1;
    e.fn(q);
    if (q >= 1) { fx.splice(k, 1); k--; }
  }
  // sway: the stack turns a few degrees, slowly, once it is built
  if (st.swayT !== undefined) {
    const s = t - st.swayT, amp = 11 * Math.PI / 180 * eInOut(clamp01(s / 2500));
    st.alpha = amp * Math.sin(s / 16000 * Math.PI * 2);
  }
  for (let i = 0; i < N; i++) st.lift[i] += (st.liftTo[i] - st.lift[i]) * 0.14;
  render(t);
  requestAnimationFrame(loop);
}

// ================= mobile: the same six layers as a list; the light runs through the icons =================
const ico = (L, on) => {
  const root = L.id === 'kernel';
  const c = on ? '#63DDD7' : root ? '#10C4BE' : 'rgba(99,221,215,.7)';
  const k = root ? `<rect x="15.5" y="11" width="13" height="2.6" fill="#10C4BE" filter="url(#mg)"/><rect class="kf" x="15.5" y="11" width="13" height="2.6" fill="#E8FFFD" opacity="0"/>` : '';
  return `<svg class="ico" viewBox="0 0 44 30"><defs><filter id="mg" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="1.4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
      <polygon points="2,15 22,5 42,15 22,25" fill="#10C4BE" fill-opacity="${on || root ? .28 : .12}" stroke="${c}" stroke-width="1"/>
      <polygon points="2,15 22,25 22,28 2,18" fill="#10C4BE" fill-opacity=".22" stroke="${c}" stroke-width=".8"/>
      <polygon points="22,25 42,15 42,18 22,28" fill="#10C4BE" fill-opacity=".12" stroke="${c}" stroke-width=".8"/>${k}</svg>`;
};
(function buildMobile() {
  let h = '<div class="mline"></div><div class="mpk"></div><div class="mpk t"></div>';
  LAYERS.forEach((L, i) => {
    const on = i === sel;
    h += `<div class="row ${on ? 'on' : ''} ${L.id === 'kernel' ? 'root' : ''}" data-i="${i}">${ico(L, on)}
      <div class="rt"><b>${L.name}<span class="s">${L.sub}</span></b><span class="e">${L.ev}</span></div><i>${on ? '⌄' : '›'}</i>
      <div class="detw"${on ? '' : ' hidden'}><div class="det fx-panel">${detail(L)}</div></div></div>`;
  });
  document.getElementById('mlist').innerHTML = h;
})();
const mlist = $('#mlist'), mrows = $$('.row', mlist), mline = $('.mline', mlist), [mpk, mpk2] = $$('.mpk', mlist);
let mOpen = sel;
const LINE_TOP = 22;
const iconY = (row) => { const r = $('.ico', row).getBoundingClientRect(); return r.top + r.height / 2 - mlist.getBoundingClientRect().top; };
const lineEnd = () => iconY(mrows[N - 1]);
function fitLine(ms = 0) {
  const t0 = performance.now();
  const step = () => {
    mline.style.bottom = 'auto'; mline.style.height = (lineEnd() - LINE_TOP) + 'px';
    if (performance.now() - t0 < ms) requestAnimationFrame(step);
  };
  step();
}
function setRowOn(i, on) {
  const row = mrows[i];
  row.classList.toggle('on', on);
  $('i', row).textContent = on ? '⌄' : '›';
  $('.ico', row).outerHTML = ico(LAYERS[i], on);
}
function expand(w) {
  w.hidden = false;
  if (STILL) return;
  const h = w.offsetHeight;
  w.animate([{ height: '0px', marginTop: '0px', opacity: 0 }, { height: h + 'px', marginTop: '12px', opacity: 1 }], { duration: 350, easing: EASE });
}
function collapse(w) {
  if (STILL) { w.hidden = true; return; }
  const h = w.offsetHeight;
  w.animate([{ height: h + 'px', marginTop: '12px', opacity: 1 }, { height: '0px', marginTop: '0px', opacity: 0 }], { duration: 350, easing: EASE, fill: 'forwards' })
    .finished.then((a) => { w.hidden = true; a.cancel(); }, () => {});
}
mrows.forEach((row, i) => row.addEventListener('click', () => {
  [mpk, mpk2].forEach((p) => p.getAnimations().forEach((a) => a.cancel()));
  const prev = mOpen;
  if (prev !== null) { setRowOn(prev, false); $('.detw', mrows[prev]).getAnimations().forEach((a) => a.cancel()); collapse($('.detw', mrows[prev])); }
  if (prev === i) { mOpen = null; fitLine(STILL ? 0 : 420); return; }
  mOpen = i; setRowOn(i, true); $('.detw', row).getAnimations().forEach((a) => a.cancel()); expand($('.detw', row));
  fitLine(STILL ? 0 : 420);
}));

const icoFlash = (row, color, delay = 0) => $('.ico', row).animate([{ filter: 'brightness(1)' },
  { filter: `brightness(1.8) drop-shadow(0 0 4px ${color})`, offset: .35 }, { filter: 'brightness(1)' }], { duration: 650, delay: Math.max(0, delay) });
function mRun(p, dir, dur, delay, color, onEnd) {
  const len = lineEnd() - LINE_TOP, a = LINE_TOP - 8, b = LINE_TOP + len - 8;
  const anim = p.animate([
    { transform: `translateY(${dir > 0 ? a : b}px)`, opacity: 0 }, { opacity: 1, offset: 0.07 }, { opacity: 1, offset: 0.9 },
    { transform: `translateY(${dir > 0 ? b : a}px)`, opacity: 0 }], { duration: dur, delay, easing: 'linear' });
  mrows.forEach((row) => {
    const f = (iconY(row) - LINE_TOP) / len, tt = (dir > 0 ? f : 1 - f) * dur;
    icoFlash(row, color, delay + tt - 160);
  });
  if (onEnd) anim.finished.then(onEnd, () => {});
}
function introMobile() {
  // the product as one slab: every icon sits on the first, then the list opens downward
  const y0 = iconY(mrows[0]);
  mrows.forEach((row, i) => {
    const ic = $('.ico', row), dy = y0 - iconY(row) + i * 3.4, d = 820 + i * 55;
    ic.animate([{ transform: `translateY(${dy}px)`, opacity: 0 }, { transform: `translateY(${dy}px)`, opacity: 1 }], { duration: 400, delay: 300, fill: 'backwards' });
    play(ic, [{ transform: `translateY(${dy}px)` }, { transform: 'translateY(0px)' }], { duration: 900, delay: d, easing: 'cubic-bezier(.2,1.25,.35,1)' });
    for (const el of [$('.rt', row), $('i', row)]) play(el, [{ opacity: 0, transform: 'translateX(-6px)' }, { opacity: 1, transform: 'none' }], { duration: 420, delay: d + 560 });
    const w = $('.detw', row);
    if (!w.hidden) play(w, [{ opacity: 0 }, { opacity: 1 }], { duration: 450, delay: d + 700 });
    row.style.borderTopColor = 'transparent'; row.style.borderBottomColor = 'transparent';
    setTimeout(() => { row.style.borderTopColor = ''; row.style.borderBottomColor = ''; }, d + 520);
  });
  play(mline, [{ transform: 'scaleY(0)' }, { transform: 'scaleY(1)' }], { duration: 1150, delay: 820, easing: 'cubic-bezier(.3,.8,.3,1)' });
  // AI Agents build each layer (cyan), then a Tool test runs down (teal) and the kernel lights
  mrows.forEach((row, i) => icoFlash(row, 'rgba(191,243,240,.95)', 2050 + i * 90));
  mRun(mpk2, 1, 850, 2750, 'rgba(99,221,215,.95)');
  $('.kf', mlist).animate([{ opacity: 0 }, { opacity: 1, offset: .3 }, { opacity: 0 }], { duration: 900, delay: 3600 });
  play($('.mhint'), [{ opacity: 0 }, { opacity: 1 }], { duration: 600, delay: 3900 });
  // then the product runs: a request down, its answer back up
  const cycle = () => {
    icoFlash(mrows[0], 'rgba(242,255,254,.95)');
    mRun(mpk, 1, 1150, 0, 'rgba(191,243,240,.9)', () => {
      const kf = $('.kf', mlist); if (kf) kf.animate([{ opacity: 0 }, { opacity: .8, offset: .3 }, { opacity: 0 }], { duration: 650 });
      mRun(mpk2, -1, 1000, 120, 'rgba(99,221,215,.9)');
    });
  };
  setTimeout(() => { cycle(); setInterval(cycle, 2600); }, 4400);
}

// ---------- start when visible (standalone: at load; in an iframe: when it scrolls into view) ----------
function revealMsg() {
  $$('.msg > *').forEach((el, k) => play(el, [{ opacity: 0, transform: 'translateY(10px)' }, { opacity: 1, transform: 'none' }], { duration: 600, delay: k * 90 }));
}
function start() {
  T0 = performance.now(); window.__t0 = T0;
  revealMsg();
  if (MOBILE) { introMobile(); if (HERO) { introDesktop(); render(0); requestAnimationFrame(loop); } }
  else { introDesktop(); render(0); requestAnimationFrame(loop); }
  document.documentElement.classList.remove('pre');
}
if (STILL) {
  render(0);
} else {
  render(0);
  const io = new IntersectionObserver((es) => {
    if (es.some((e) => e.isIntersecting)) { io.disconnect(); start(); }
  }, { threshold: 0.35 });
  io.observe(MOBILE && !HERO ? mlist : stage);
}


  return () => {
    t_.forEach((id) => W_.clearTimeout(id)); i_.forEach((id) => W_.clearInterval(id)); r_.forEach((id) => W_.cancelAnimationFrame(id));
    o_.forEach((o) => o.disconnect()); off_.forEach((f) => f());
    // running animations are left alone: the site detaches the scene next, and cancelling them would reject
    // the `finished` promises the scene still awaits (AbortError)
  };
}
